import { Award } from "./awards.types";

export const AWARDS: Award[] = [
  // Legacy Trophies (Coach-Awarded End of Season)
  {
    id: "coach-choice",
    kind: "Trophy",
    name: "Coach's Choice",
    tier: "Legacy",
    category: "SeasonalLegacy",
    description: "Special recognition from coach for exceptional character and dedication.",
    iconName: "trophy-coach-choice",
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["Coach", "Special"]
  },
  {
    id: "most-improved",
    kind: "Trophy", 
    name: "Most Improved",
    tier: "Legacy",
    category: "SeasonalLegacy",
    description: "Awarded to the player who showed the greatest improvement over the season.",
    iconName: "trophy-most-improved",
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["Improvement", "Season"]
  },
  {
    id: "leadership",
    kind: "Trophy",
    name: "Leadership",
    tier: "Legacy", 
    category: "SeasonalLegacy",
    description: "For demonstrating exceptional leadership on and off the court.",
    iconName: "trophy-leadership",
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["Leadership", "Character"]
  },
  {
    id: "mvp-season",
    kind: "Trophy",
    name: "Season MVP",
    tier: "Legacy",
    category: "SeasonalLegacy", 
    description: "Most Valuable Player for the entire season.",
    iconName: "trophy-mvp-season",
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["MVP", "Season"]
  },
  {
    id: "championship",
    kind: "Trophy",
    name: "Championship",
    tier: "Legacy",
    category: "SeasonalLegacy",
    description: "Team championship winner - the ultimate achievement.",
    iconName: "trophy-championship", 
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["Championship", "Team"]
  },

  // Team Trophies (Coach-Awarded for Specific Achievements)
  {
    id: "team-mvp",
    kind: "Trophy",
    name: "Team MVP",
    tier: "Team",
    category: "InGamePerformance",
    description: "Most Valuable Player recognition from coach.",
    iconName: "trophy-team-mvp",
    progressKind: "manual", 
    triggerSources: ["coachAward"],
    tags: ["MVP", "Team"]
  },
  {
    id: "team-hustle",
    kind: "Trophy",
    name: "Team Hustle",
    tier: "Team",
    category: "InGamePerformance",
    description: "Hustle Player recognition from coach.",
    iconName: "trophy-team-hustle",
    progressKind: "manual",
    triggerSources: ["coachAward"], 
    tags: ["Hustle", "Team"]
  },

  // Hall of Famer Badges (Elite - Yellow)
  {
    id: "superstar",
    kind: "Badge",
    name: "Superstar",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 10 MVP awards - the pinnacle of individual performance.",
    iconName: "badge-superstar",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 10, label: "MVP awards" },
    triggerSources: ["coachAward"],
    tags: ["MVP", "Elite"]
  },
  {
    id: "legend",
    kind: "Badge", 
    name: "Legend",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 10 Hustle awards - legendary work ethic and determination.",
    iconName: "badge-legend",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 10, label: "Hustle awards" },
    triggerSources: ["coachAward"],
    tags: ["Hustle", "Elite"]
  },
  {
    id: "century",
    kind: "Badge",
    name: "Century",
    tier: "HallOfFamer", 
    category: "Attendance",
    description: "Attended 100 total practices - shows incredible dedication.",
    iconName: "badge-century",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 100, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practices", "Elite"]
  },
  {
    id: "training-master",
    kind: "Badge",
    name: "Training Master", 
    tier: "HallOfFamer",
    category: "TrainingProgram",
    description: "Completed 25 training programs - mastery through dedication.",
    iconName: "badge-training-master",
    progressKind: "counter",
    counterOf: { stat: "trainingProgramsCompleted", target: 25, label: "programs completed" },
    triggerSources: ["trainingCompletion"],
    tags: ["Training", "Elite"]
  },
  {
    id: "immortal",
    kind: "Badge",
    name: "Immortal",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Achieved immortal status through exceptional all-around excellence.",
    iconName: "badge-immortal",
    progressKind: "composite",
    composite: [
      { stat: "mvpCount", min: 8 },
      { stat: "hustleCount", min: 8 },
      { stat: "practicesTotal", min: 75 }
    ],
    triggerSources: ["mixed"],
    tags: ["Immortal", "Ultimate"]
  },
  {
    id: "goat",
    kind: "Badge",
    name: "GOAT",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Greatest Of All Time - the ultimate UYP Basketball achievement.",
    iconName: "badge-goat",
    progressKind: "composite",
    composite: [
      { stat: "mvpCount", min: 15 },
      { stat: "hustleCount", min: 12 },
      { stat: "teammateCount", min: 10 },
      { stat: "practicesTotal", min: 100 },
      { stat: "gamesTotal", min: 75 }
    ],
    triggerSources: ["mixed"],
    tags: ["GOAT", "Ultimate"]
  },
  {
    id: "dynasty",
    kind: "Badge",
    name: "Dynasty",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Multi-year excellence spanning 3+ seasons.",
    iconName: "badge-dynasty",
    progressKind: "counter",
    counterOf: { stat: "yearsActive", target: 3, label: "years active" },
    triggerSources: ["longevity"],
    tags: ["Dynasty", "Years"]
  },
  {
    id: "foundation-god",
    kind: "Badge",
    name: "Foundation God",
    tier: "HallOfFamer",
    category: "TrainingProgram",
    description: "Completed the entire Foundation Program - ultimate mastery.",
    iconName: "badge-foundation-god",
    progressKind: "completeAll",
    completeAll: { setId: "foundation_all", label: "Complete Foundation Program" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Complete"]
  },
  {
    id: "iron-man",
    kind: "Badge",
    name: "Iron Man",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Perfect season attendance - never missed a single event.",
    iconName: "badge-iron-man",
    progressKind: "composite",
    composite: [
      { stat: "playedEveryPracticeSeason", min: 1 },
      { stat: "playedEveryGameSeason", min: 1 },
      { stat: "rsvpedEveryEventSeason", min: 1 }
    ],
    triggerSources: ["attendance"],
    tags: ["Perfect", "Season"]
  },
  {
    id: "clutch-god",
    kind: "Badge",
    name: "Clutch God",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 8 Clutch awards - godlike in pressure situations.",
    iconName: "badge-clutch-god",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 8, label: "Clutch awards" },
    triggerSources: ["coachAward"],
    tags: ["Clutch", "God"]
  },
  {
    id: "mentor",
    kind: "Badge",
    name: "Mentor",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Brought 3 new players to UYP - becoming a mentor.",
    iconName: "badge-mentor",
    progressKind: "counter",
    counterOf: { stat: "referrals", target: 3, label: "referrals" },
    triggerSources: ["community"],
    tags: ["Mentor", "Community"]
  },
  {
    id: "teammate-god",
    kind: "Badge",
    name: "Teammate God",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 8 Teammate awards - godlike teammate spirit.",
    iconName: "badge-teammate-god",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 8, label: "Teammate awards" },
    triggerSources: ["coachAward"],
    tags: ["Teammate", "God"]
  },
  {
    id: "comeback-legend",
    kind: "Badge",
    name: "Comeback Legend",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 8 Comeback awards - legendary comeback ability.",
    iconName: "badge-comeback-legend",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 8, label: "Comeback awards" },
    triggerSources: ["coachAward"],
    tags: ["Comeback", "Legend"]
  },
  {
    id: "game-god",
    kind: "Badge",
    name: "Game God",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Played in 100 games - godlike game experience.",
    iconName: "badge-game-god",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 100, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Games", "God"]
  },
  {
    id: "skills-legend",
    kind: "Badge",
    name: "Skills Legend",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Attended 100 skills sessions - legendary skill dedication.",
    iconName: "badge-skills-legend",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 100, label: "skills sessions" },
    triggerSources: ["attendance"],
    tags: ["Skills", "Legend"]
  },
  {
    id: "sportsmanship-god",
    kind: "Badge",
    name: "Sportsmanship God",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 8 Sportsmanship awards - godlike character.",
    iconName: "badge-sportsmanship-god",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 8, label: "sportsmanship awards" },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship", "God"]
  },
  {
    id: "student-legend",
    kind: "Badge",
    name: "Student Legend",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 8 Student awards - legendary dedication to learning.",
    iconName: "badge-student-legend",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 8, label: "student awards" },
    triggerSources: ["coachAward"],
    tags: ["Learning", "Legend"]
  },
  {
    id: "leadership-legend",
    kind: "Badge",
    name: "Leadership Legend",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 5 Lead by Example awards - legendary leadership.",
    iconName: "badge-leadership-legend",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 5, label: "leadership awards" },
    triggerSources: ["coachAward"],
    tags: ["Leadership", "Legend"]
  },
  {
    id: "practice-god",
    kind: "Badge",
    name: "Practice God",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Attended 150 practices - godlike dedication to practice.",
    iconName: "badge-practice-god",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 150, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practices", "God"]
  },
  {
    id: "training-god",
    kind: "Badge",
    name: "Training God",
    tier: "HallOfFamer",
    category: "TrainingProgram",
    description: "Completed 50 training programs - godlike training dedication.",
    iconName: "badge-training-god",
    progressKind: "counter",
    counterOf: { stat: "trainingProgramsCompleted", target: 50, label: "programs completed" },
    triggerSources: ["trainingCompletion"],
    tags: ["Training", "God"]
  },
  {
    id: "streak-legend",
    kind: "Badge",
    name: "Streak Legend",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Attended 30 practices in a row - legendary consistency.",
    iconName: "badge-streak-legend",
    progressKind: "streak",
    streakOf: { stat: "practiceStreak", target: 30, label: "consecutive practices" },
    triggerSources: ["attendance"],
    tags: ["Practices", "Streak"]
  },
  {
    id: "foundation-legend",
    kind: "Badge",
    name: "Foundation Legend",
    tier: "HallOfFamer",
    category: "TrainingProgram",
    description: "Watched 80 Foundation Program videos - legendary knowledge.",
    iconName: "badge-foundation-legend",
    progressKind: "counter",
    counterOf: { stat: "foundation.totalVideos", target: 80, label: "videos watched" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Legend"]
  },
  {
    id: "ambassador",
    kind: "Badge",
    name: "Ambassador",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Brought 5 new players to UYP - true ambassador.",
    iconName: "badge-ambassador",
    progressKind: "counter",
    counterOf: { stat: "referrals", target: 5, label: "referrals" },
    triggerSources: ["community"],
    tags: ["Ambassador", "Community"]
  },
  {
    id: "ultimate",
    kind: "Badge",
    name: "Ultimate",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Ultimate achievement - mastery across all areas of UYP Basketball.",
    iconName: "badge-ultimate",
    progressKind: "composite",
    composite: [
      { stat: "mvpCount", min: 12 },
      { stat: "hustleCount", min: 10 },
      { stat: "teammateCount", min: 8 },
      { stat: "clutchCount", min: 6 },
      { stat: "practicesTotal", min: 100 },
      { stat: "gamesTotal", min: 75 },
      { stat: "trainingProgramsCompleted", min: 20 }
    ],
    triggerSources: ["mixed"],
    tags: ["Ultimate", "Complete"]
  },
  {
    id: "fnh-god",
    kind: "Badge",
    name: "FNH God",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Played in 50 Friday Night Hoops games - godlike FNH dedication.",
    iconName: "badge-fnh-god",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 50, label: "FNH games" },
    triggerSources: ["attendance"],
    tags: ["FNH", "God"]
  },
  {
    id: "holiday-hero",
    kind: "Badge",
    name: "Holiday Hero",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Played in 10 holiday games - true dedication to the team.",
    iconName: "badge-holiday-hero",
    progressKind: "counter",
    counterOf: { stat: "holidayGamesCount", target: 10, label: "holiday games" },
    triggerSources: ["attendance"],
    tags: ["Holiday", "Hero"]
  },
  {
    id: "tournament-legend",
    kind: "Badge",
    name: "Tournament Legend",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Perfect tournament attendance - checked in to every game.",
    iconName: "badge-tournament-legend",
    progressKind: "counter",
    counterOf: { stat: "tournamentAllGamesCheckedIn", target: 1, label: "perfect tournament" },
    triggerSources: ["attendance"],
    tags: ["Tournament", "Perfect"]
  },
  {
    id: "rsvp-god",
    kind: "Badge",
    name: "RSVP God",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "100 on-time RSVPs in a season - godlike planning.",
    iconName: "badge-rsvp-god",
    progressKind: "counter",
    counterOf: { stat: "rsvpsOnTimeSeason", target: 100, label: "on-time RSVPs" },
    triggerSources: ["attendance"],
    tags: ["RSVP", "God"]
  },
  {
    id: "legacy-builder",
    kind: "Badge",
    name: "Legacy Builder",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Built a lasting legacy spanning 5+ years at UYP.",
    iconName: "badge-legacy-builder",
    progressKind: "counter",
    counterOf: { stat: "yearsActive", target: 5, label: "years active" },
    triggerSources: ["longevity"],
    tags: ["Legacy", "Builder"]
  },
  {
    id: "hall-of-famer",
    kind: "Badge",
    name: "Hall of Famer",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Inducted into the UYP Basketball Hall of Fame - the highest honor.",
    iconName: "badge-hall-of-famer",
    progressKind: "composite",
    composite: [
      { stat: "mvpCount", min: 20 },
      { stat: "hustleCount", min: 15 },
      { stat: "teammateCount", min: 12 },
      { stat: "practicesTotal", min: 150 },
      { stat: "gamesTotal", min: 100 },
      { stat: "yearsActive", min: 4 }
    ],
    triggerSources: ["mixed"],
    tags: ["HallOfFame", "Honor"]
  },
  {
    id: "perfection",
    kind: "Badge",
    name: "Perfection",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Achieved perfection - the ultimate badge in UYP Basketball.",
    iconName: "badge-perfection",
    progressKind: "composite",
    composite: [
      { stat: "mvpCount", min: 25 },
      { stat: "hustleCount", min: 20 },
      { stat: "teammateCount", min: 15 },
      { stat: "clutchCount", min: 10 },
      { stat: "sportsmanshipCount", min: 10 },
      { stat: "practicesTotal", min: 200 },
      { stat: "gamesTotal", min: 150 },
      { stat: "trainingProgramsCompleted", min: 50 },
      { stat: "yearsActive", min: 5 }
    ],
    triggerSources: ["mixed"],
    tags: ["Perfection", "Ultimate"]
  },

  // Superstar Badges (Advanced - Purple) - 20 badges
  {
    id: "star-player",
    kind: "Badge",
    name: "Star Player",
    tier: "Superstar",
    category: "InGamePerformance", 
    description: "Earned 5 MVP awards - a true star on the court.",
    iconName: "badge-star-player",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 5, label: "MVP awards" },
    triggerSources: ["coachAward"],
    tags: ["MVP", "Performance"]
  },
  {
    id: "workhorse",
    kind: "Badge",
    name: "Workhorse", 
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Hustle awards - relentless effort and energy.",
    iconName: "badge-workhorse", 
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 5, label: "Hustle awards" },
    triggerSources: ["coachAward"],
    tags: ["Hustle", "Work Ethic"]
  },
  {
    id: "team-captain",
    kind: "Badge",
    name: "Team Captain",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Teammate awards - natural captain and leader.",
    iconName: "badge-team-captain",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 5, label: "Teammate awards" },
    triggerSources: ["coachAward"],
    tags: ["Teammate", "Captain"]
  },
  {
    id: "clutch-legend",
    kind: "Badge",
    name: "Clutch Legend",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Clutch awards - legendary in pressure moments.",
    iconName: "badge-clutch-legend",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 5, label: "Clutch awards" },
    triggerSources: ["coachAward"],
    tags: ["Clutch", "Legend"]
  },
  {
    id: "comeback-artist",
    kind: "Badge",
    name: "Comeback Artist",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Comeback awards - artist of the comeback.",
    iconName: "badge-comeback-artist",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 5, label: "Comeback awards" },
    triggerSources: ["coachAward"],
    tags: ["Comeback", "Artist"]
  },
  {
    id: "practice-veteran",
    kind: "Badge",
    name: "Practice Veteran",
    tier: "Superstar",
    category: "Attendance",
    description: "Attended 50 total practices - veteran-level commitment.",
    iconName: "badge-practice-veteran",
    progressKind: "counter", 
    counterOf: { stat: "practicesTotal", target: 50, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practices", "Veteran"]
  },
  {
    id: "game-master",
    kind: "Badge",
    name: "Game Master",
    tier: "Superstar",
    category: "Attendance",
    description: "Played in 35 games - mastering game situations.",
    iconName: "badge-game-master",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 35, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Games", "Mastery"]
  },
  {
    id: "skills-elite",
    kind: "Badge",
    name: "Skills Elite",
    tier: "Superstar",
    category: "Attendance",
    description: "Attended 35 skills sessions - elite skill development.",
    iconName: "badge-skills-elite",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 35, label: "skills sessions" },
    triggerSources: ["attendance"],
    tags: ["Skills", "Elite"]
  },
  {
    id: "fnh-champion",
    kind: "Badge",
    name: "FNH Champion",
    tier: "Superstar",
    category: "Attendance",
    description: "Played in 15 Friday Night Hoops games - champion status.",
    iconName: "badge-fnh-champion",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 15, label: "FNH games" },
    triggerSources: ["attendance"],
    tags: ["FNH", "Champion"]
  },
  {
    id: "training-expert",
    kind: "Badge",
    name: "Training Expert",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Completed 15 training programs - expert-level skill development.",
    iconName: "badge-training-expert",
    progressKind: "counter",
    counterOf: { stat: "trainingProgramsCompleted", target: 15, label: "programs completed" },
    triggerSources: ["trainingCompletion"],
    tags: ["Training", "Expert"]
  },
  {
    id: "practice-streak-15",
    kind: "Badge",
    name: "Practice Streak 15",
    tier: "Superstar",
    category: "Attendance",
    description: "Attended 15 practices in a row - superstar consistency!",
    iconName: "badge-practice-streak-15",
    progressKind: "streak",
    streakOf: { stat: "practiceStreak", target: 15, label: "consecutive practices" },
    triggerSources: ["attendance"],
    tags: ["Practices", "Streak"]
  },
  {
    id: "foundation-expert",
    kind: "Badge",
    name: "Foundation Expert",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Watched 40 Foundation Program videos - true expert.",
    iconName: "badge-foundation-expert",
    progressKind: "counter",
    counterOf: { stat: "foundation.totalVideos", target: 40, label: "videos watched" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Expert"]
  },
  {
    id: "skills-perfectionist",
    kind: "Badge",
    name: "Skills Perfectionist",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Completed 25 Foundation skills videos - perfectionist approach.",
    iconName: "badge-skills-perfectionist",
    progressKind: "counter",
    counterOf: { stat: "foundation.skillsCompleted", target: 25, label: "skills videos" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Perfection"]
  },
  {
    id: "tactical-genius",
    kind: "Badge",
    name: "Tactical Genius",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Completed 12 Foundation basketball IQ videos - tactical genius.",
    iconName: "badge-tactical-genius",
    progressKind: "counter",
    counterOf: { stat: "foundation.iqCompleted", target: 12, label: "IQ videos" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Tactics"]
  },
  {
    id: "physical-specimen",
    kind: "Badge",
    name: "Physical Specimen",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Completed 12 Foundation S&C videos - physical excellence.",
    iconName: "badge-physical-specimen",
    progressKind: "counter",
    counterOf: { stat: "foundation.scCompleted", target: 12, label: "S&C videos" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Physical"]
  },
  {
    id: "model-athlete",
    kind: "Badge",
    name: "Model Athlete",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Sportsmanship awards - model of athletic character.",
    iconName: "badge-model-athlete",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 5, label: "sportsmanship awards" },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship", "Model"]
  },
  {
    id: "master-student",
    kind: "Badge",
    name: "Master Student",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Student awards - master of continuous learning.",
    iconName: "badge-master-student",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 5, label: "student awards" },
    triggerSources: ["coachAward"],
    tags: ["Learning", "Mastery"]
  },
  {
    id: "leadership-elite",
    kind: "Badge",
    name: "Leadership Elite",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 3 Lead by Example awards - elite leadership qualities.",
    iconName: "badge-leadership-elite",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 3, label: "leadership awards" },
    triggerSources: ["coachAward"],
    tags: ["Leadership", "Elite"]
  },
  {
    id: "superstar-package",
    kind: "Badge",
    name: "Superstar Package",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Complete superstar - excellence across all performance areas.",
    iconName: "badge-superstar-package",
    progressKind: "composite",
    composite: [
      { stat: "mvpCount", min: 3 },
      { stat: "hustleCount", min: 3 },
      { stat: "teammateCount", min: 3 },
      { stat: "clutchCount", min: 2 }
    ],
    triggerSources: ["coachAward"],
    tags: ["Complete", "Superstar"]
  },
  {
    id: "iron-man",
    kind: "Badge",
    name: "Iron Man",
    tier: "Superstar",
    category: "Attendance",
    description: "Exceptional durability and attendance across the season.",
    iconName: "badge-iron-man",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 40, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Durability", "Iron"]
  },

  // All-Star Badges (Solid - Blue) - 20 badges
  {
    id: "standout",
    kind: "Badge", 
    name: "Standout",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 MVP awards - consistently stands out from the crowd.",
    iconName: "badge-standout",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 3, label: "MVP awards" },
    triggerSources: ["coachAward"],
    tags: ["MVP", "Consistent"]
  },
  {
    id: "grinder",
    kind: "Badge",
    name: "Grinder",
    tier: "AllStar", 
    category: "InGamePerformance",
    description: "Earned 3 Hustle awards - never stops grinding and working hard.",
    iconName: "badge-grinder",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 3, label: "Hustle awards" },
    triggerSources: ["coachAward"],
    tags: ["Hustle", "Persistence"]
  },
  {
    id: "team-leader",
    kind: "Badge",
    name: "Team Leader",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Teammate awards - a true leader on and off the court.",
    iconName: "badge-team-leader",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 3, label: "Teammate awards" },
    triggerSources: ["coachAward"],
    tags: ["Teammate", "Leadership"]
  },
  {
    id: "clutch-master",
    kind: "Badge",
    name: "Clutch Master",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Clutch awards - master of pressure situations.",
    iconName: "badge-clutch-master",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 3, label: "Clutch awards" },
    triggerSources: ["coachAward"],
    tags: ["Clutch", "Pressure"]
  },
  {
    id: "comeback-specialist",
    kind: "Badge",
    name: "Comeback Specialist",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Comeback awards - specializes in fighting back.",
    iconName: "badge-comeback-specialist",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 3, label: "Comeback awards" },
    triggerSources: ["coachAward"],
    tags: ["Comeback", "Resilient"]
  },
  {
    id: "practice-regular",
    kind: "Badge",
    name: "Practice Regular",
    tier: "AllStar",
    category: "Attendance",
    description: "Attended 25 total practices - regular attendance shows commitment.",
    iconName: "badge-practice-regular", 
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 25, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practices", "Regular"]
  },
  {
    id: "game-experienced",
    kind: "Badge",
    name: "Game Experienced",
    tier: "AllStar",
    category: "Attendance",
    description: "Played in 20 games - gaining extensive experience.",
    iconName: "badge-game-experienced",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 20, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Games", "Experience"]
  },
  {
    id: "skills-dedicated",
    kind: "Badge",
    name: "Skills Dedicated",
    tier: "AllStar",
    category: "Attendance",
    description: "Attended 20 skills sessions - dedicated to skill development.",
    iconName: "badge-skills-dedicated",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 20, label: "skills sessions" },
    triggerSources: ["attendance"],
    tags: ["Skills", "Dedication"]
  },
  {
    id: "fnh-veteran",
    kind: "Badge",
    name: "FNH Veteran",
    tier: "AllStar",
    category: "Attendance",
    description: "Played in 10 Friday Night Hoops games - veteran status.",
    iconName: "badge-fnh-veteran",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 10, label: "FNH games" },
    triggerSources: ["attendance"],
    tags: ["FNH", "Veteran"]
  },
  {
    id: "training-specialist", 
    kind: "Badge",
    name: "Training Specialist",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Completed 10 training programs - developing specialized skills.",
    iconName: "badge-training-specialist",
    progressKind: "counter",
    counterOf: { stat: "trainingProgramsCompleted", target: 10, label: "programs completed" },
    triggerSources: ["trainingCompletion"],
    tags: ["Training", "Specialist"]
  },
  {
    id: "practice-streak-10",
    kind: "Badge",
    name: "Practice Streak 10",
    tier: "AllStar",
    category: "Attendance",
    description: "Attended 10 practices in a row - impressive consistency!",
    iconName: "badge-practice-streak-10",
    progressKind: "streak",
    streakOf: { stat: "practiceStreak", target: 10, label: "consecutive practices" },
    triggerSources: ["attendance"],
    tags: ["Practices", "Streak"]
  },
  {
    id: "foundation-scholar",
    kind: "Badge",
    name: "Foundation Scholar",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Watched 25 Foundation Program videos - true scholar.",
    iconName: "badge-foundation-scholar",
    progressKind: "counter",
    counterOf: { stat: "foundation.totalVideos", target: 25, label: "videos watched" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Scholar"]
  },
  {
    id: "skills-master",
    kind: "Badge",
    name: "Skills Master",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Completed 15 Foundation skills videos - mastering fundamentals.",
    iconName: "badge-skills-master",
    progressKind: "counter",
    counterOf: { stat: "foundation.skillsCompleted", target: 15, label: "skills videos" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Skills"]
  },
  {
    id: "basketball-iq",
    kind: "Badge",
    name: "Basketball IQ",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Completed 8 Foundation basketball IQ videos - high basketball intelligence.",
    iconName: "badge-basketball-iq",
    progressKind: "counter",
    counterOf: { stat: "foundation.iqCompleted", target: 8, label: "IQ videos" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "IQ"]
  },
  {
    id: "strength-conditioning",
    kind: "Badge",
    name: "Strength & Conditioning",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Completed 8 Foundation S&C videos - building physical strength.",
    iconName: "badge-strength-conditioning",
    progressKind: "counter",
    counterOf: { stat: "foundation.scCompleted", target: 8, label: "S&C videos" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Strength"]
  },
  {
    id: "exemplary-sport",
    kind: "Badge",
    name: "Exemplary Sport",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Sportsmanship awards - exemplary character.",
    iconName: "badge-exemplary-sport",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 3, label: "sportsmanship awards" },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship", "Character"]
  },
  {
    id: "dedicated-student",
    kind: "Badge",
    name: "Dedicated Student",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Student awards - dedicated to learning and growth.",
    iconName: "badge-dedicated-student",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 3, label: "student awards" },
    triggerSources: ["coachAward"],
    tags: ["Learning", "Growth"]
  },
  {
    id: "example-setter",
    kind: "Badge",
    name: "Example Setter",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 2 Lead by Example awards - setting the standard.",
    iconName: "badge-example-setter",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 2, label: "leadership awards" },
    triggerSources: ["coachAward"],
    tags: ["Leadership", "Example"]
  },
  {
    id: "consistent-performer",
    kind: "Badge",
    name: "Consistent Performer",
    tier: "AllStar",
    category: "Attendance",
    description: "Maintained excellent attendance across multiple months.",
    iconName: "badge-consistent-performer",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 20, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Consistency", "Performance"]
  },
  {
    id: "all-around-player",
    kind: "Badge",
    name: "All-Around Player",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Showing excellence in multiple areas of the game.",
    iconName: "badge-all-around-player",
    progressKind: "composite",
    composite: [
      { stat: "mvpCount", min: 2 },
      { stat: "hustleCount", min: 2 },
      { stat: "teammateCount", min: 2 }
    ],
    triggerSources: ["coachAward"],
    tags: ["Versatile", "Excellence"]
  },

  // Starter Badges (First Achievements - Green) - 20 badges
  {
    id: "rising-star",
    kind: "Badge",
    name: "Rising Star",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned 2 MVP awards - a star is rising!",
    iconName: "badge-rising-star",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 2, label: "MVP awards" },
    triggerSources: ["coachAward"],
    tags: ["MVP", "Rising"]
  },
  {
    id: "hustler",
    kind: "Badge",
    name: "Hustler", 
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned 2 Hustle awards - showing that winning effort!",
    iconName: "badge-hustler",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 2, label: "Hustle awards" },
    triggerSources: ["coachAward"],
    tags: ["Hustle", "Effort"]
  },
  {
    id: "team-first",
    kind: "Badge",
    name: "Team First",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned 2 Teammate awards - putting team before self.",
    iconName: "badge-team-first",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 2, label: "Teammate awards" },
    triggerSources: ["coachAward"],
    tags: ["Teammate", "Selfless"]
  },
  {
    id: "clutch-performer",
    kind: "Badge",
    name: "Clutch Performer",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned 2 Clutch awards - stepping up when it matters.",
    iconName: "badge-clutch-performer",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 2, label: "Clutch awards" },
    triggerSources: ["coachAward"],
    tags: ["Clutch", "Pressure"]
  },
  {
    id: "comeback-kid",
    kind: "Badge",
    name: "Comeback Kid",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned 2 Comeback awards - never giving up.",
    iconName: "badge-comeback-kid",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 2, label: "Comeback awards" },
    triggerSources: ["coachAward"],
    tags: ["Comeback", "Resilient"]
  },
  {
    id: "practice-starter",
    kind: "Badge",
    name: "Practice Starter",
    tier: "Starter",
    category: "Attendance",
    description: "Attended 10 total practices - building the foundation of success.",
    iconName: "badge-practice-starter",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 10, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practices", "Foundation"]
  },
  {
    id: "game-veteran",
    kind: "Badge",
    name: "Game Veteran",
    tier: "Starter",
    category: "Attendance",
    description: "Played in 10 games - gaining valuable experience.",
    iconName: "badge-game-veteran",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 10, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Games", "Experience"]
  },
  {
    id: "skills-regular",
    kind: "Badge",
    name: "Skills Regular",
    tier: "Starter",
    category: "Attendance",
    description: "Attended 10 skills sessions - committed to improvement.",
    iconName: "badge-skills-regular",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 10, label: "skills sessions" },
    triggerSources: ["attendance"],
    tags: ["Skills", "Development"]
  },
  {
    id: "fnh-regular",
    kind: "Badge",
    name: "FNH Regular",
    tier: "Starter",
    category: "Attendance",
    description: "Played in 5 Friday Night Hoops games.",
    iconName: "badge-fnh-regular",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 5, label: "FNH games" },
    triggerSources: ["attendance"],
    tags: ["FNH", "Regular"]
  },
  {
    id: "training-beginner",
    kind: "Badge",
    name: "Training Beginner",
    tier: "Starter", 
    category: "TrainingProgram",
    description: "Completed 5 training programs - beginning the journey to excellence.",
    iconName: "badge-training-beginner",
    progressKind: "counter",
    counterOf: { stat: "trainingProgramsCompleted", target: 5, label: "programs completed" },
    triggerSources: ["trainingCompletion"],
    tags: ["Training", "Beginner"]
  },
  {
    id: "practice-streak-5",
    kind: "Badge",
    name: "Practice Streak 5",
    tier: "Starter",
    category: "Attendance",
    description: "Attended 5 practices in a row - building momentum!",
    iconName: "badge-practice-streak-5",
    progressKind: "streak",
    streakOf: { stat: "practiceStreak", target: 5, label: "consecutive practices" },
    triggerSources: ["attendance"],
    tags: ["Practices", "Streak"]
  },
  {
    id: "foundation-student",
    kind: "Badge",
    name: "Foundation Student",
    tier: "Starter",
    category: "TrainingProgram",
    description: "Watched 10 Foundation Program videos.",
    iconName: "badge-foundation-student",
    progressKind: "counter",
    counterOf: { stat: "foundation.totalVideos", target: 10, label: "videos watched" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Student"]
  },
  {
    id: "skills-focused",
    kind: "Badge",
    name: "Skills Focused",
    tier: "Starter",
    category: "TrainingProgram",
    description: "Completed 5 Foundation skills videos.",
    iconName: "badge-skills-focused",
    progressKind: "counter",
    counterOf: { stat: "foundation.skillsCompleted", target: 5, label: "skills videos" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Skills"]
  },
  {
    id: "court-awareness",
    kind: "Badge",
    name: "Court Awareness",
    tier: "Starter",
    category: "TrainingProgram",
    description: "Completed 3 Foundation basketball IQ videos.",
    iconName: "badge-court-awareness",
    progressKind: "counter",
    counterOf: { stat: "foundation.iqCompleted", target: 3, label: "IQ videos" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "IQ"]
  },
  {
    id: "strength-builder",
    kind: "Badge",
    name: "Strength Builder",
    tier: "Starter",
    category: "TrainingProgram",
    description: "Completed 3 Foundation strength & conditioning videos.",
    iconName: "badge-strength-builder",
    progressKind: "counter",
    counterOf: { stat: "foundation.scCompleted", target: 3, label: "S&C videos" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Strength"]
  },
  {
    id: "good-sport",
    kind: "Badge",
    name: "Good Sport",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned 2 Sportsmanship awards - playing the right way.",
    iconName: "badge-good-sport",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 2, label: "sportsmanship awards" },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship", "Character"]
  },
  {
    id: "eager-learner",
    kind: "Badge",
    name: "Eager Learner",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned 2 Student awards - always ready to learn.",
    iconName: "badge-eager-learner",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 2, label: "student awards" },
    triggerSources: ["coachAward"],
    tags: ["Learning", "Growth"]
  },
  {
    id: "role-model",
    kind: "Badge",
    name: "Role Model",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned 1 Lead by Example award - setting a good example.",
    iconName: "badge-role-model",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 1, label: "leadership awards" },
    triggerSources: ["coachAward"],
    tags: ["Leadership", "Example"]
  },
  {
    id: "reliable",
    kind: "Badge",
    name: "Reliable",
    tier: "Starter",
    category: "Attendance",
    description: "Maintained good attendance for the month.",
    iconName: "badge-reliable",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 8, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Reliability", "Consistency"]
  },
  {
    id: "committed",
    kind: "Badge",
    name: "Committed",
    tier: "Starter",
    category: "Attendance",
    description: "Showing commitment to team and improvement.",
    iconName: "badge-committed",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 5, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Commitment", "Dedication"]
  },

  // Prospect Badges (Entry Level - Grey) - 20 badges
  {
    id: "first-mvp",
    kind: "Badge",
    name: "First MVP",
    tier: "Prospect",
    category: "InGamePerformance",
    description: "For earning your very first MVP award.",
    iconName: "badge-first-mvp",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 1, label: "MVP awards" },
    triggerSources: ["coachAward"],
    tags: ["MVP", "Milestone"]
  },
  {
    id: "first-hustle",
    kind: "Badge",
    name: "First Hustle", 
    tier: "Prospect",
    category: "InGamePerformance",
    description: "For earning your very first Hustle award.",
    iconName: "badge-first-hustle",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 1, label: "Hustle awards" },
    triggerSources: ["coachAward"],
    tags: ["Hustle", "Milestone"]
  },
  {
    id: "first-teammate",
    kind: "Badge",
    name: "First Teammate",
    tier: "Prospect",
    category: "InGamePerformance",
    description: "For earning your very first Teammate award.",
    iconName: "badge-first-teammate",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 1, label: "Teammate awards" },
    triggerSources: ["coachAward"],
    tags: ["Teammate", "Milestone"]
  },
  {
    id: "first-clutch",
    kind: "Badge",
    name: "First Clutch",
    tier: "Prospect",
    category: "InGamePerformance",
    description: "For earning your very first Clutch award.",
    iconName: "badge-first-clutch",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 1, label: "Clutch awards" },
    triggerSources: ["coachAward"],
    tags: ["Clutch", "Milestone"]
  },
  {
    id: "first-comeback",
    kind: "Badge",
    name: "First Comeback",
    tier: "Prospect",
    category: "InGamePerformance",
    description: "For earning your very first Comeback award.",
    iconName: "badge-first-comeback",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 1, label: "Comeback awards" },
    triggerSources: ["coachAward"],
    tags: ["Comeback", "Milestone"]
  },
  {
    id: "first-practice",
    kind: "Badge",
    name: "First Practice",
    tier: "Prospect",
    category: "Attendance",
    description: "For attending your very first practice.",
    iconName: "badge-first-practice",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 1, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practices", "First"]
  },
  {
    id: "first-game",
    kind: "Badge",
    name: "First Game",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in your very first game.",
    iconName: "badge-first-game",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 1, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Games", "First"]
  },
  {
    id: "first-skills",
    kind: "Badge",
    name: "First Skills",
    tier: "Prospect",
    category: "Attendance",
    description: "For attending your very first skills session.",
    iconName: "badge-first-skills",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 1, label: "skills sessions" },
    triggerSources: ["attendance"],
    tags: ["Skills", "First"]
  },
  {
    id: "first-fnh",
    kind: "Badge",
    name: "First FNH",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in your very first Friday Night Hoops game.",
    iconName: "badge-first-fnh",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 1, label: "FNH games" },
    triggerSources: ["attendance"],
    tags: ["FNH", "First"]
  },
  {
    id: "first-training",
    kind: "Badge",
    name: "First Training",
    tier: "Prospect",
    category: "TrainingProgram",
    description: "For completing your very first training program.",
    iconName: "badge-first-training", 
    progressKind: "counter",
    counterOf: { stat: "trainingProgramsCompleted", target: 1, label: "programs completed" },
    triggerSources: ["trainingCompletion"],
    tags: ["Training", "First"]
  },
  {
    id: "rookie",
    kind: "Badge",
    name: "Rookie",
    tier: "Prospect",
    category: "InGamePerformance",
    description: "Welcome to UYP Basketball - your journey begins!",
    iconName: "badge-rookie",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 1, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Welcome", "Beginning"]
  },
  {
    id: "early-bird",
    kind: "Badge",
    name: "Early Bird",
    tier: "Prospect",
    category: "Attendance",
    description: "Attended 3 practices - building good habits early.",
    iconName: "badge-early-bird",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 3, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practices", "Habit"]
  },
  {
    id: "game-ready",
    kind: "Badge",
    name: "Game Ready",
    tier: "Prospect",
    category: "Attendance",
    description: "Played in 3 games - you're getting game experience!",
    iconName: "badge-game-ready",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 3, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Games", "Experience"]
  },
  {
    id: "skills-starter",
    kind: "Badge",
    name: "Skills Starter",
    tier: "Prospect",
    category: "Attendance",
    description: "Attended 3 skills sessions - focusing on fundamentals.",
    iconName: "badge-skills-starter",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 3, label: "skills sessions" },
    triggerSources: ["attendance"],
    tags: ["Skills", "Fundamentals"]
  },
  {
    id: "practice-streak-3",
    kind: "Badge",
    name: "Practice Streak 3",
    tier: "Prospect",
    category: "Attendance",
    description: "Attended 3 practices in a row - consistency is key!",
    iconName: "badge-practice-streak-3",
    progressKind: "streak",
    streakOf: { stat: "practiceStreak", target: 3, label: "consecutive practices" },
    triggerSources: ["attendance"],
    tags: ["Practices", "Streak"]
  },
  {
    id: "foundation-explorer",
    kind: "Badge",
    name: "Foundation Explorer",
    tier: "Prospect",
    category: "TrainingProgram",
    description: "Started exploring Foundation Program content.",
    iconName: "badge-foundation-explorer",
    progressKind: "counter",
    counterOf: { stat: "foundation.totalVideos", target: 5, label: "videos watched" },
    triggerSources: ["trainingCompletion"],
    tags: ["Foundation", "Explorer"]
  },
  {
    id: "team-player",
    kind: "Badge",
    name: "Team Player",
    tier: "Prospect",
    category: "InGamePerformance",
    description: "Showing great teamwork and sportsmanship.",
    iconName: "badge-team-player",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 1, label: "teammate recognition" },
    triggerSources: ["coachAward"],
    tags: ["Teamwork", "Sportsmanship"]
  },
  {
    id: "effort-award",
    kind: "Badge",
    name: "Effort Award",
    tier: "Prospect",
    category: "InGamePerformance",
    description: "Always giving maximum effort on the court.",
    iconName: "badge-effort-award",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 1, label: "effort recognition" },
    triggerSources: ["coachAward"],
    tags: ["Effort", "Hustle"]
  },
  {
    id: "positive-attitude",
    kind: "Badge",
    name: "Positive Attitude",
    tier: "Prospect",
    category: "InGamePerformance",
    description: "Maintaining a positive attitude through wins and losses.",
    iconName: "badge-positive-attitude",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 1, label: "sportsmanship awards" },
    triggerSources: ["coachAward"],
    tags: ["Attitude", "Sportsmanship"]
  },
  {
    id: "coachable",
    kind: "Badge",
    name: "Coachable",
    tier: "Prospect",
    category: "InGamePerformance",
    description: "Listens well and applies coaching feedback.",
    iconName: "badge-coachable",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 1, label: "student awards" },
    triggerSources: ["coachAward"],
    tags: ["Coachable", "Learning"]
  }
];

export const TIER_ORDER = ["Prospect", "Starter", "AllStar", "Superstar", "HallOfFamer", "Team", "Legacy"];