
import { Award } from "./awards.types";

export const AWARDS: Award[] = [
  // ===== TROPHIES =====
  
  // Legacy Trophies (Yearly) — 1 winner across all UYP
  {
    id: "uyp-heart-and-hustle",
    kind: "Trophy",
    name: "The UYP Heart and Hustle Award",
    tier: "Legacy",
    category: "SeasonalLegacy",
    description: "Yearly award recognizing the single player who most consistently gave their all in practices and games.",
    iconName: "trophy-heart-hustle",
    progressKind: "none",
    triggerSources: ["coachAward"],
    tags: ["Yearly", "Legacy"]
  },
  {
    id: "uyp-spirit-award",
    kind: "Trophy",
    name: "The Spirit Award",
    tier: "Legacy",
    category: "SeasonalLegacy",
    description: "Yearly award for the one player who best maintained a positive attitude and lifted team morale on and off the court.",
    iconName: "trophy-spirit",
    progressKind: "none",
    triggerSources: ["coachAward"],
    tags: ["Yearly", "Legacy"]
  },

  // Team Trophies (Seasonal) — coach-awarded per team
  {
    id: "team-mvp",
    kind: "Trophy",
    name: "MVP (Most Valuable Player)",
    tier: "Team",
    category: "SeasonalLegacy",
    description: "Coach-awarded seasonal MVP for team impact.",
    iconName: "trophy-mvp",
    progressKind: "none",
    triggerSources: ["coachAward"],
    tags: ["Coach Award"]
  },
  {
    id: "coachs-award",
    kind: "Trophy",
    name: "Coach's Award",
    tier: "Team",
    category: "SeasonalLegacy",
    description: "Special recognition from the coach for outstanding contribution to the team.",
    iconName: "trophy-coach",
    progressKind: "none",
    triggerSources: ["coachAward"],
    tags: ["Coach Award"]
  },
  {
    id: "most-improved-player",
    kind: "Trophy",
    name: "MIP (Most Improved Player)",
    tier: "Team",
    category: "SeasonalLegacy",
    description: "Awarded to the player who showed the most improvement throughout the season.",
    iconName: "trophy-mip",
    progressKind: "none",
    triggerSources: ["coachAward"],
    tags: ["Coach Award"]
  },

  // ===== BADGES - HALL OF FAMER (Yellow) =====
  
  {
    id: "superstar-10x-mvp",
    kind: "Badge",
    name: "Superstar (10× MVP)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For demonstrating a consistent pattern of dominance.",
    iconName: "badge-10x-mvp",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 10, label: "MVP awards" },
    triggerSources: ["coachAward"],
    tags: ["MVP"]
  },
  {
    id: "prime-time-10x-clutch",
    kind: "Badge",
    name: "Prime Time (10× Clutch)",
    tier: "HallOfFamer",
    category: "InGamePerformance", 
    description: "For being known to deliver in the biggest moments.",
    iconName: "badge-10x-clutch",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 10, label: "Clutch awards" },
    triggerSources: ["coachAward"],
    tags: ["Clutch"]
  },
  {
    id: "force-of-will-10x-comeback",
    kind: "Badge",
    name: "Force of Will (10× Comeback)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For an unbreakable spirit that refuses to lose.",
    iconName: "badge-10x-comeback",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 10, label: "Comeback awards" },
    triggerSources: ["coachAward"],
    tags: ["Comeback"]
  },
  {
    id: "relentless-10x-hustle",
    kind: "Badge",
    name: "Relentless (10× Hustle)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For a motor that never stops.",
    iconName: "badge-10x-hustle",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 10, label: "Hustle awards" },
    triggerSources: ["coachAward"],
    tags: ["Hustle"]
  },
  {
    id: "the-linchpin-10x-teammate",
    kind: "Badge",
    name: "The Linchpin (10× Teammate)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For being absolutely essential to team cohesion.",
    iconName: "badge-10x-teammate",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 10, label: "Teammate awards" },
    triggerSources: ["coachAward"],
    tags: ["Teammate"]
  },
  {
    id: "spirit-of-the-game-10x-sportsmanship",
    kind: "Badge",
    name: "Spirit of the Game (10× Sportsmanship)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For embodying the highest ideals of fair play.",
    iconName: "badge-10x-sportsmanship",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 10, label: "Sportsmanship awards" },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship"]
  },
  {
    id: "coach-on-the-court-10x-student",
    kind: "Badge",
    name: "Coach on the Court (10× Student)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For understanding the game on a deeper, strategic level.",
    iconName: "badge-10x-student",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 10, label: "Student awards" },
    triggerSources: ["coachAward"],
    tags: ["Student"]
  },
  {
    id: "the-paragon-10x-lead-by-example",
    kind: "Badge",
    name: "The Paragon (10× Lead by Example)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For being the ultimate embodiment of how to prepare and play.",
    iconName: "badge-10x-lead-by-example",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 10, label: "Lead by Example awards" },
    triggerSources: ["coachAward"],
    tags: ["Lead by Example"]
  },
  {
    id: "coachs-choice",
    kind: "Badge",
    name: "Coach's Choice",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For earning each of the eight core coach awards at least once.",
    iconName: "badge-coachs-choice",
    progressKind: "counter",
    composite: [
      { stat: "mvpCount", min: 1 },
      { stat: "clutchCount", min: 1 },
      { stat: "comebackCount", min: 1 },
      { stat: "hustleCount", min: 1 },
      { stat: "teammateCount", min: 1 },
      { stat: "sportsmanshipCount", min: 1 },
      { stat: "studentCount", min: 1 },
      { stat: "leadByExampleCount", min: 1 }
    ],
    triggerSources: ["coachAward"],
    tags: ["Composite"]
  },
  {
    id: "the-trifecta",
    kind: "Badge",
    name: "The Trifecta",
    tier: "HallOfFamer",
    category: "SeasonalLegacy",
    description: "For earning an MVP, Hustle, and Teammate award in the same season.",
    iconName: "badge-trifecta",
    progressKind: "counter",
    composite: [
      { stat: "mvp", min: 1, seasonScoped: true },
      { stat: "hustle", min: 1, seasonScoped: true },
      { stat: "teammate", min: 1, seasonScoped: true }
    ],
    triggerSources: ["coachAward"],
    tags: ["Seasonal", "Composite"]
  },
  {
    id: "character-captain",
    kind: "Badge",
    name: "Character Captain",
    tier: "HallOfFamer",
    category: "SeasonalLegacy",
    description: "For earning a Hustle, Teammate, and Sportsmanship award in the same season.",
    iconName: "badge-character-captain",
    progressKind: "counter",
    composite: [
      { stat: "hustle", min: 1, seasonScoped: true },
      { stat: "teammate", min: 1, seasonScoped: true },
      { stat: "sportsmanship", min: 1, seasonScoped: true }
    ],
    triggerSources: ["coachAward"],
    tags: ["Seasonal", "Composite"]
  },
  {
    id: "practice-legend",
    kind: "Badge",
    name: "Practice Legend",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "For attending 250 total team practices.",
    iconName: "badge-practice-legend",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 250, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practice"]
  },
  {
    id: "skills-virtuoso",
    kind: "Badge",
    name: "Skills Virtuoso",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "For attending 250 total skills sessions.",
    iconName: "badge-skills-virtuoso",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 250, label: "skills sessions attended" },
    triggerSources: ["attendance"],
    tags: ["Skills"]
  },
  {
    id: "franchise-player",
    kind: "Badge",
    name: "Franchise Player",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "For playing in 250 total games.",
    iconName: "badge-franchise-player",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 250, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Games"]
  },
  {
    id: "fnh-hall-of-famer",
    kind: "Badge",
    name: "FNH Hall of Famer",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "For playing in 250 total FNH games.",
    iconName: "badge-fnh-hall-of-famer",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 250, label: "FNH games played" },
    triggerSources: ["attendance"],
    tags: ["FNH"]
  },
  {
    id: "dynasty-member",
    kind: "Badge",
    name: "Dynasty Member",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "For being an active member of the team for five full years.",
    iconName: "badge-dynasty-member",
    progressKind: "counter",
    counterOf: { stat: "yearsActive", target: 5, label: "years active" },
    triggerSources: ["attendance"],
    tags: ["Years"]
  },
  {
    id: "digital-triple-crown",
    kind: "Badge",
    name: "The Digital Triple Crown",
    tier: "HallOfFamer",
    category: "TrainingProgram",
    description: "Complete all Skill (36), S&C (12), and Basketball IQ (12) videos in Foundation.",
    iconName: "badge-digital-triple-crown",
    progressKind: "completeAll",
    completeAll: { setId: "foundation_all", label: "All Foundation videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation"]
  },
  {
    id: "foundation-alumnus",
    kind: "Badge",
    name: "Foundation Alumnus",
    tier: "HallOfFamer",
    category: "TrainingProgram",
    description: "Complete the 12-week Foundation program twice.",
    iconName: "badge-foundation-alumnus",
    progressKind: "counter",
    counterOf: { stat: "foundation.completedTwice", target: 1, label: "times completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation"]
  },

  // ===== BADGES - SUPERSTAR (Purple) =====
  
  {
    id: "marquee-player-5x-mvp",
    kind: "Badge",
    name: "Marquee Player (5× MVP)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For being a recognized star and reliable top performer.",
    iconName: "badge-5x-mvp",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 5, label: "MVP awards" },
    triggerSources: ["coachAward"],
    tags: ["MVP"]
  },
  {
    id: "ice-in-the-veins-5x-clutch",
    kind: "Badge",
    name: "Ice in the Veins (5× Clutch)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For thriving under pressure.",
    iconName: "badge-5x-clutch",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 5, label: "Clutch awards" },
    triggerSources: ["coachAward"],
    tags: ["Clutch"]
  },
  {
    id: "momentum-shifter-5x-comeback",
    kind: "Badge",
    name: "Momentum Shifter (5× Comeback)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For changing the tone of a game.",
    iconName: "badge-5x-comeback",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 5, label: "Comeback awards" },
    triggerSources: ["coachAward"],
    tags: ["Comeback"]
  },
  {
    id: "the-workhorse-5x-hustle",
    kind: "Badge",
    name: "The Workhorse (5× Hustle)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For having an elite work ethic.",
    iconName: "badge-5x-hustle",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 5, label: "Hustle awards" },
    triggerSources: ["coachAward"],
    tags: ["Hustle"]
  },
  {
    id: "the-cornerstone-5x-teammate",
    kind: "Badge",
    name: "The Cornerstone (5× Teammate)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For being a player the team is built around emotionally.",
    iconName: "badge-5x-teammate",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 5, label: "Teammate awards" },
    triggerSources: ["coachAward"],
    tags: ["Teammate"]
  },
  {
    id: "the-ambassador-5x-sportsmanship",
    kind: "Badge",
    name: "The Ambassador (5× Sportsmanship)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For being a positive representative of the team.",
    iconName: "badge-5x-sportsmanship",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 5, label: "Sportsmanship awards" },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship"]
  },
  {
    id: "the-tactician-5x-student",
    kind: "Badge",
    name: "The Tactician (5× Student)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For a high in-game IQ.",
    iconName: "badge-5x-student",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 5, label: "Student awards" },
    triggerSources: ["coachAward"],
    tags: ["Student"]
  },
  {
    id: "the-blueprint-5x-lead-by-example",
    kind: "Badge",
    name: "The Blueprint (5× Lead by Example)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For providing a model for others to follow.",
    iconName: "badge-5x-lead-by-example",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 5, label: "Lead by Example awards" },
    triggerSources: ["coachAward"],
    tags: ["Lead by Example"]
  },
  {
    id: "the-pillar",
    kind: "Badge",
    name: "The Pillar",
    tier: "Superstar",
    category: "Attendance",
    description: "For attending every single scheduled practice in a season.",
    iconName: "badge-pillar",
    progressKind: "counter",
    composite: [{ stat: "playedEveryPracticeSeason", min: 1 }],
    triggerSources: ["attendance", "rsvp"],
    tags: ["Perfect Attendance"]
  },
  {
    id: "ironman",
    kind: "Badge",
    name: "Ironman",
    tier: "Superstar",
    category: "Attendance",
    description: "For playing in every single game of a season.",
    iconName: "badge-ironman",
    progressKind: "counter",
    composite: [{ stat: "playedEveryGameSeason", min: 1 }],
    triggerSources: ["attendance", "rsvp"],
    tags: ["Perfect Attendance"]
  },
  {
    id: "fnh-ironman",
    kind: "Badge",
    name: "FNH Ironman",
    tier: "Superstar",
    category: "Attendance",
    description: "For playing in every FNH game in a single season.",
    iconName: "badge-fnh-ironman",
    progressKind: "counter",
    composite: [{ stat: "playedEveryFnhSeason", min: 1 }],
    triggerSources: ["attendance", "rsvp"],
    tags: ["Perfect Attendance"]
  },
  {
    id: "practice-centurion",
    kind: "Badge",
    name: "Practice Centurion",
    tier: "Superstar",
    category: "Attendance",
    description: "For attending 100 total team practices.",
    iconName: "badge-practice-centurion",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 100, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practice"]
  },
  {
    id: "skills-specialist",
    kind: "Badge",
    name: "Skills Specialist",
    tier: "Superstar",
    category: "Attendance",
    description: "For attending 100 total skills sessions.",
    iconName: "badge-skills-specialist",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 100, label: "skills sessions attended" },
    triggerSources: ["attendance"],
    tags: ["Skills"]
  },
  {
    id: "century-club",
    kind: "Badge",
    name: "Century Club",
    tier: "Superstar",
    category: "Attendance",
    description: "For playing in 100 total games.",
    iconName: "badge-century-club",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 100, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Games"]
  },
  {
    id: "fnh-legend",
    kind: "Badge",
    name: "FNH Legend",
    tier: "Superstar",
    category: "Attendance",
    description: "For playing in 100 total FNH games.",
    iconName: "badge-fnh-legend",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 100, label: "FNH games played" },
    triggerSources: ["attendance"],
    tags: ["FNH"]
  },
  {
    id: "team-veteran",
    kind: "Badge",
    name: "Team Veteran",
    tier: "Superstar",
    category: "Attendance",
    description: "For being an active member of the team for three full years.",
    iconName: "badge-team-veteran",
    progressKind: "counter",
    counterOf: { stat: "yearsActive", target: 3, label: "years active" },
    triggerSources: ["attendance"],
    tags: ["Years"]
  },
  {
    id: "foundation-graduate",
    kind: "Badge",
    name: "Foundation Graduate",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Complete all 60 Foundation videos in the 12-week program.",
    iconName: "badge-foundation-graduate",
    progressKind: "counter",
    counterOf: { stat: "foundation.totalVideos", target: 60, label: "videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation"]
  },
  {
    id: "technique-titan",
    kind: "Badge",
    name: "Technique Titan",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Complete all 36 Skill videos in Foundation.",
    iconName: "badge-technique-titan",
    progressKind: "counter",
    counterOf: { stat: "foundation.skillsCompleted", target: 36, label: "skill videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation", "Skills"]
  },
  {
    id: "peak-performer",
    kind: "Badge",
    name: "Peak Performer",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Complete all 12 S&C videos in Foundation.",
    iconName: "badge-peak-performer",
    progressKind: "counter",
    counterOf: { stat: "foundation.scCompleted", target: 12, label: "S&C videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation", "S&C"]
  },
  {
    id: "basketball-savant",
    kind: "Badge",
    name: "Basketball Savant",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Complete all 12 Basketball IQ videos in Foundation.",
    iconName: "badge-basketball-savant",
    progressKind: "counter",
    counterOf: { stat: "foundation.iqCompleted", target: 12, label: "IQ videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation", "IQ"]
  },
  {
    id: "perfect-attendance-online",
    kind: "Badge",
    name: "Perfect Attendance: Online",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Complete Foundation videos for 12 consecutive weeks.",
    iconName: "badge-perfect-attendance-online",
    progressKind: "counter",
    composite: [{ stat: "foundation.weeklyCompleted12", min: 1 }],
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation", "Streak"]
  },

  // ===== BADGES - ALL-STAR (Blue) =====
  
  {
    id: "game-changer-3x-mvp",
    kind: "Badge",
    name: "Game Changer (3× MVP)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For consistently making a pivotal impact.",
    iconName: "badge-3x-mvp",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 3, label: "MVP awards" },
    triggerSources: ["coachAward"],
    tags: ["MVP"]
  },
  {
    id: "the-closer-3x-clutch",
    kind: "Badge",
    name: "The Closer (3× Clutch)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For making multiple high-pressure plays.",
    iconName: "badge-3x-clutch",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 3, label: "Clutch awards" },
    triggerSources: ["coachAward"],
    tags: ["Clutch"]
  },
  {
    id: "the-sparkplug-3x-comeback",
    kind: "Badge",
    name: "The Sparkplug (3× Comeback)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For consistently igniting team rallies.",
    iconName: "badge-3x-comeback",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 3, label: "Comeback awards" },
    triggerSources: ["coachAward"],
    tags: ["Comeback"]
  },
  {
    id: "the-engine-3x-hustle",
    kind: "Badge",
    name: "The Engine (3× Hustle)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For being a consistent source of energy.",
    iconName: "badge-3x-hustle",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 3, label: "Hustle awards" },
    triggerSources: ["coachAward"],
    tags: ["Hustle"]
  },
  {
    id: "the-glue-3x-teammate",
    kind: "Badge",
    name: "The Glue (3× Teammate)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For being a positive and unifying presence.",
    iconName: "badge-3x-teammate",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 3, label: "Teammate awards" },
    triggerSources: ["coachAward"],
    tags: ["Teammate"]
  },
  {
    id: "class-act-3x-sportsmanship",
    kind: "Badge",
    name: "Class Act (3× Sportsmanship)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For consistent respectful conduct.",
    iconName: "badge-3x-sportsmanship",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 3, label: "Sportsmanship awards" },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship"]
  },
  {
    id: "the-protege-3x-student",
    kind: "Badge",
    name: "The Protégé (3× Student)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For being exceptionally coachable and attentive.",
    iconName: "badge-3x-student",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 3, label: "Student awards" },
    triggerSources: ["coachAward"],
    tags: ["Student"]
  },
  {
    id: "the-standard-3x-lead-by-example",
    kind: "Badge",
    name: "The Standard (3× Lead by Example)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For setting the bar for effort and execution.",
    iconName: "badge-3x-lead-by-example",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 3, label: "Lead by Example awards" },
    triggerSources: ["coachAward"],
    tags: ["Lead by Example"]
  },
  {
    id: "the-dependable",
    kind: "Badge",
    name: "The Dependable",
    tier: "AllStar",
    category: "Attendance",
    description: "For submitting a timely RSVP for every event in a season.",
    iconName: "badge-dependable",
    progressKind: "counter",
    composite: [{ stat: "rsvpedEveryEventSeason", min: 1 }],
    triggerSources: ["rsvp"],
    tags: ["RSVP"]
  },
  {
    id: "recruiter",
    kind: "Badge",
    name: "Recruiter",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Awarded for referring a new player who joins.",
    iconName: "badge-recruiter",
    progressKind: "counter",
    counterOf: { stat: "referrals", target: 1, label: "player referrals" },
    triggerSources: ["coachAward"],
    tags: ["Referral"]
  },
  {
    id: "practice-fiend",
    kind: "Badge",
    name: "Practice Fiend",
    tier: "AllStar",
    category: "Attendance",
    description: "For attending 50 total practices.",
    iconName: "badge-practice-fiend",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 50, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practice"]
  },
  {
    id: "skills-devotee",
    kind: "Badge",
    name: "Skills Devotee",
    tier: "AllStar",
    category: "Attendance",
    description: "For attending 50 total skills sessions.",
    iconName: "badge-skills-devotee",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 50, label: "skills sessions attended" },
    triggerSources: ["attendance"],
    tags: ["Skills"]
  },
  {
    id: "seasoned-competitor",
    kind: "Badge",
    name: "Seasoned Competitor",
    tier: "AllStar",
    category: "Attendance",
    description: "For playing in 50 total games.",
    iconName: "badge-seasoned-competitor",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 50, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Games"]
  },
  {
    id: "fnh-veteran",
    kind: "Badge",
    name: "FNH Veteran",
    tier: "AllStar",
    category: "Attendance",
    description: "For playing in 50 total FNH games.",
    iconName: "badge-fnh-veteran",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 50, label: "FNH games played" },
    triggerSources: ["attendance"],
    tags: ["FNH"]
  },
  {
    id: "first-year-anniversary",
    kind: "Badge",
    name: "First Year Anniversary",
    tier: "AllStar",
    category: "Attendance",
    description: "For being an active member of the team for one full year.",
    iconName: "badge-first-year-anniversary",
    progressKind: "counter",
    counterOf: { stat: "yearsActive", target: 1, label: "years active" },
    triggerSources: ["attendance"],
    tags: ["Years"]
  },
  {
    id: "half-time-adjustments",
    kind: "Badge",
    name: "Half-Time Adjustments",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Complete 30 Foundation videos.",
    iconName: "badge-half-time-adjustments",
    progressKind: "counter",
    counterOf: { stat: "foundation.totalVideos", target: 30, label: "videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation"]
  },
  {
    id: "monthly-module-master",
    kind: "Badge",
    name: "Monthly Module Master",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Complete Foundation videos for 4 consecutive weeks.",
    iconName: "badge-monthly-module-master",
    progressKind: "counter",
    composite: [{ stat: "foundation.monthly4", min: 1 }],
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation", "Streak"]
  },
  {
    id: "skills-sharpshooter",
    kind: "Badge",
    name: "Skills Sharpshooter",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Complete 18 Skill videos in Foundation.",
    iconName: "badge-skills-sharpshooter",
    progressKind: "counter",
    counterOf: { stat: "foundation.skillsCompleted", target: 18, label: "skill videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation", "Skills"]
  },
  {
    id: "conditioning-specialist",
    kind: "Badge",
    name: "Conditioning Specialist",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Complete 6 S&C videos in Foundation.",
    iconName: "badge-conditioning-specialist",
    progressKind: "counter",
    counterOf: { stat: "foundation.scCompleted", target: 6, label: "S&C videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation", "S&C"]
  },
  {
    id: "basketball-scholar",
    kind: "Badge",
    name: "Basketball Scholar",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Complete 6 Basketball IQ videos in Foundation.",
    iconName: "badge-basketball-scholar",
    progressKind: "counter",
    counterOf: { stat: "foundation.iqCompleted", target: 6, label: "IQ videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Foundation", "IQ"]
  },

  // ===== BADGES - STARTER (Green) =====
  
  {
    id: "locked-in",
    kind: "Badge",
    name: "Locked In",
    tier: "Starter",
    category: "Attendance",
    description: "For attending 10 consecutive scheduled practices.",
    iconName: "badge-locked-in",
    progressKind: "streak",
    streakOf: { stat: "practiceStreak", target: 10, label: "consecutive practices" },
    triggerSources: ["attendance"],
    tags: ["Practice", "Streak"]
  },
  {
    id: "on-the-ball",
    kind: "Badge",
    name: "On the Ball",
    tier: "Starter",
    category: "Attendance",
    description: "For submitting a timely RSVP for 10 consecutive events.",
    iconName: "badge-on-the-ball",
    progressKind: "streak",
    streakOf: { stat: "rsvpStreak", target: 10, label: "consecutive RSVPs" },
    triggerSources: ["rsvp"],
    tags: ["RSVP", "Streak"]
  },
  {
    id: "tournament-titan",
    kind: "Badge",
    name: "Tournament Titan",
    tier: "Starter",
    category: "Attendance",
    description: "For checking into all games in a single tournament.",
    iconName: "badge-tournament-titan",
    progressKind: "counter",
    composite: [{ stat: "tournamentAllGamesCheckedIn", min: 1 }],
    triggerSources: ["attendance"],
    tags: ["Tournament"]
  },
  {
    id: "dedicated-grinder",
    kind: "Badge",
    name: "Dedicated Grinder",
    tier: "Starter",
    category: "Attendance",
    description: "For attending 25 total practices.",
    iconName: "badge-dedicated-grinder",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 25, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practice"]
  },
  {
    id: "skills-seeker",
    kind: "Badge",
    name: "Skills Seeker",
    tier: "Starter",
    category: "Attendance",
    description: "For attending 25 total skills sessions.",
    iconName: "badge-skills-seeker",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 25, label: "skills sessions attended" },
    triggerSources: ["attendance"],
    tags: ["Skills"]
  },
  {
    id: "regular-competitor",
    kind: "Badge",
    name: "Regular Competitor",
    tier: "Starter",
    category: "Attendance",
    description: "For playing in 25 total games.",
    iconName: "badge-regular-competitor",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 25, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Games"]
  },
  {
    id: "fnh-regular",
    kind: "Badge",
    name: "FNH Regular",
    tier: "Starter",
    category: "Attendance",
    description: "For playing in 25 total FNH games.",
    iconName: "badge-fnh-regular",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 25, label: "FNH games played" },
    triggerSources: ["attendance"],
    tags: ["FNH"]
  },
  {
    id: "game-mvp",
    kind: "Badge",
    name: "Game MVP",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Instrumental in the team's performance during a single game.",
    iconName: "badge-game-mvp",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 1, label: "MVP awards" },
    triggerSources: ["coachAward"],
    tags: ["MVP"]
  },
  {
    id: "clutch-player",
    kind: "Badge",
    name: "Clutch Player",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Given for making a game-changing play under pressure.",
    iconName: "badge-clutch-player",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 1, label: "Clutch awards" },
    triggerSources: ["coachAward"],
    tags: ["Clutch"]
  },
  {
    id: "comeback-kid",
    kind: "Badge",
    name: "Comeback Kid",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Given for energy that was instrumental in a team rally.",
    iconName: "badge-comeback-kid",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 1, label: "Comeback awards" },
    triggerSources: ["coachAward"],
    tags: ["Comeback"]
  },
  {
    id: "sportsmanship-award",
    kind: "Badge",
    name: "Sportsmanship Award",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Display of outstanding sportsmanship.",
    iconName: "badge-sportsmanship-award",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 1, label: "Sportsmanship awards" },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship"]
  },
  {
    id: "hustle-award",
    kind: "Badge",
    name: "Hustle Award",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Relentless hustle and effort.",
    iconName: "badge-hustle-award",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 1, label: "Hustle awards" },
    triggerSources: ["coachAward"],
    tags: ["Hustle"]
  },
  {
    id: "teammate-award",
    kind: "Badge",
    name: "Teammate Award",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Encouraging, supportive, or unselfish play.",
    iconName: "badge-teammate-award",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 1, label: "Teammate awards" },
    triggerSources: ["coachAward"],
    tags: ["Teammate"]
  },
  {
    id: "student-of-the-game",
    kind: "Badge",
    name: "Student of the Game",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Exceptional listening skills and attentiveness.",
    iconName: "badge-student-of-the-game",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 1, label: "Student awards" },
    triggerSources: ["coachAward"],
    tags: ["Student"]
  },
  {
    id: "lead-by-example",
    kind: "Badge",
    name: "Lead by Example",
    tier: "Starter",
    category: "InGamePerformance",
    description: "For flawlessly demonstrating a drill or skill.",
    iconName: "badge-lead-by-example",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 1, label: "Lead by Example awards" },
    triggerSources: ["coachAward"],
    tags: ["Lead by Example"]
  },

  // ===== BADGES - PROSPECT (Grey) =====
  
  {
    id: "checked-in",
    kind: "Badge",
    name: "Checked In",
    tier: "Prospect",
    category: "Attendance",
    description: "For checking into any UYP event.",
    iconName: "badge-checked-in",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 1, label: "events attended" },
    triggerSources: ["attendance"],
    tags: ["First Time"]
  },
  {
    id: "road-warrior",
    kind: "Badge",
    name: "Road Warrior",
    tier: "Prospect",
    category: "Attendance",
    description: "For checking into an event at a different location.",
    iconName: "badge-road-warrior",
    progressKind: "none", // Manual award for away games
    triggerSources: ["attendance"],
    tags: ["Away Game"]
  },
  {
    id: "holiday-hero",
    kind: "Badge",
    name: "Holiday Hero",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in a game on a major holiday.",
    iconName: "badge-holiday-hero",
    progressKind: "counter",
    counterOf: { stat: "holidayGamesCount", target: 1, label: "holiday games played" },
    triggerSources: ["attendance"],
    tags: ["Holiday"]
  },
  {
    id: "the-debut",
    kind: "Badge",
    name: "The Debut",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in your very first game.",
    iconName: "badge-debut",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 1, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["First Time"]
  },
  {
    id: "friday-follower",
    kind: "Badge",
    name: "Friday Follower",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in your first Friday Night Hoops game.",
    iconName: "badge-friday-follower",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 1, label: "FNH games played" },
    triggerSources: ["attendance"],
    tags: ["FNH", "First Time"]
  },
  {
    id: "heating-up",
    kind: "Badge",
    name: "Heating Up",
    tier: "Prospect",
    category: "Attendance",
    description: "For attending 5 consecutive scheduled practices.",
    iconName: "badge-heating-up",
    progressKind: "streak",
    streakOf: { stat: "practiceStreak", target: 5, label: "consecutive practices" },
    triggerSources: ["attendance"],
    tags: ["Practice", "Streak"]
  },
  {
    id: "game-planner",
    kind: "Badge",
    name: "Game Planner",
    tier: "Prospect",
    category: "Attendance",
    description: "For RSVPing to a Game within its proper window.",
    iconName: "badge-game-planner",
    progressKind: "counter",
    counterOf: { stat: "rsvpsOnTimeSeason", target: 1, label: "timely RSVPs" },
    triggerSources: ["rsvp"],
    tags: ["RSVP", "First Time"]
  },
  {
    id: "practice-planner",
    kind: "Badge",
    name: "Practice Planner",
    tier: "Prospect",
    category: "Attendance",
    description: "For RSVPing to a Practice, Skill, or FNH event.",
    iconName: "badge-practice-planner",
    progressKind: "counter",
    counterOf: { stat: "rsvpsOnTimeSeason", target: 1, label: "timely RSVPs" },
    triggerSources: ["rsvp"],
    tags: ["RSVP", "First Time"]
  },
  {
    id: "first-reps",
    kind: "Badge",
    name: "First Reps",
    tier: "Prospect",
    category: "Attendance",
    description: "For attending 10 total practices.",
    iconName: "badge-first-reps",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 10, label: "practices attended" },
    triggerSources: ["attendance"],
    tags: ["Practice"]
  },
  {
    id: "skill-starter",
    kind: "Badge",
    name: "Skill Starter",
    tier: "Prospect",
    category: "Attendance",
    description: "For attending 10 total skills sessions.",
    iconName: "badge-skill-starter",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 10, label: "skills sessions attended" },
    triggerSources: ["attendance"],
    tags: ["Skills"]
  },
  {
    id: "first-ten",
    kind: "Badge",
    name: "First Ten",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in 10 total games.",
    iconName: "badge-first-ten",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 10, label: "games played" },
    triggerSources: ["attendance"],
    tags: ["Games"]
  },
  {
    id: "fnh-fighter",
    kind: "Badge",
    name: "FNH Fighter",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in 10 total FNH games.",
    iconName: "badge-fnh-fighter",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 10, label: "FNH games played" },
    triggerSources: ["attendance"],
    tags: ["FNH"]
  }
];

export const TIER_ORDER = ["Prospect", "Starter", "AllStar", "Superstar", "HallOfFamer", "Team", "Legacy"];
    name: "Superstar",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 10 MVP awards - the pinnacle of individual performance.",
    iconName: "badge-superstar",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 10, label: "MVP awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "prime-time",
    kind: "Badge",
    name: "Prime Time",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 10 Clutch awards - always performs when it matters most.",
    iconName: "badge-prime-time",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 10, label: "Clutch awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "force-of-will",
    kind: "Badge",
    name: "Force of Will",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 10 Comeback awards - never gives up, always fights back.",
    iconName: "badge-force-will",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 10, label: "Comeback awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "relentless",
    kind: "Badge",
    name: "Relentless",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 10 Hustle awards - demonstrates unmatched work ethic.",
    iconName: "badge-relentless",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 10, label: "Hustle awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-linchpin",
    kind: "Badge",
    name: "The Linchpin",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 10 Teammate awards - the cornerstone that holds the team together.",
    iconName: "badge-linchpin",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 10, label: "Teammate awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "spirit-of-game",
    kind: "Badge",
    name: "Spirit of the Game",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 10 Sportsmanship awards - embodies the true spirit of basketball.",
    iconName: "badge-spirit-game",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 10, label: "Sportsmanship awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "coach-on-court",
    kind: "Badge",
    name: "Coach on the Court",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 10 Student awards - demonstrates exceptional basketball IQ and learning ability.",
    iconName: "badge-coach-court",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 10, label: "Student awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-paragon",
    kind: "Badge",
    name: "The Paragon",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned 10 Lead by Example awards - the ultimate role model.",
    iconName: "badge-paragon",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 10, label: "Lead by Example awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "coachs-choice",
    kind: "Badge",
    name: "Coach's Choice",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned each of the 8 core coach awards at least once - complete versatility.",
    iconName: "badge-coach-choice",
    progressKind: "composite",
    composite: [
      { stat: "mvpCount", min: 1 },
      { stat: "clutchCount", min: 1 },
      { stat: "comebackCount", min: 1 },
      { stat: "hustleCount", min: 1 },
      { stat: "teammateCount", min: 1 },
      { stat: "sportsmanshipCount", min: 1 },
      { stat: "studentCount", min: 1 },
      { stat: "leadByExampleCount", min: 1 }
    ],
    triggerSources: ["coachAward"]
  },
  {
    id: "the-trifecta",
    kind: "Badge",
    name: "The Trifecta",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned MVP, Hustle, and Teammate awards in the same season - the complete player.",
    iconName: "badge-trifecta",
    progressKind: "composite",
    composite: [
      { stat: "mvp", min: 1, seasonScoped: true },
      { stat: "hustle", min: 1, seasonScoped: true },
      { stat: "teammate", min: 1, seasonScoped: true }
    ],
    triggerSources: ["coachAward"]
  },
  {
    id: "character-captain",
    kind: "Badge",
    name: "Character Captain",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "Earned Hustle, Teammate, and Sportsmanship awards in the same season - exemplary character.",
    iconName: "badge-character-captain",
    progressKind: "composite",
    composite: [
      { stat: "hustle", min: 1, seasonScoped: true },
      { stat: "teammate", min: 1, seasonScoped: true },
      { stat: "sportsmanship", min: 1, seasonScoped: true }
    ],
    triggerSources: ["coachAward"]
  },
  {
    id: "practice-legend",
    kind: "Badge",
    name: "Practice Legend",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Attended 250 total team practices - legendary dedication.",
    iconName: "badge-practice-legend",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 250, label: "Practices attended" },
    triggerSources: ["attendance"]
  },
  {
    id: "skills-virtuoso",
    kind: "Badge",
    name: "Skills Virtuoso",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Attended 250 skills sessions - mastery through repetition.",
    iconName: "badge-skills-virtuoso",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 250, label: "Skills sessions attended" },
    triggerSources: ["attendance"]
  },
  {
    id: "franchise-player",
    kind: "Badge",
    name: "Franchise Player",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Played in 250 games - the cornerstone of the franchise.",
    iconName: "badge-franchise-player",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 250, label: "Games played" },
    triggerSources: ["attendance"]
  },
  {
    id: "fnhof",
    kind: "Badge",
    name: "FNH Hall of Famer",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Played in 250 Friday Night Hoops games - FNH royalty.",
    iconName: "badge-fnhof",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 250, label: "FNH games played" },
    triggerSources: ["attendance"]
  },
  {
    id: "dynasty-member",
    kind: "Badge",
    name: "Dynasty Member",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "Active member for 5 full years - part of the UYP dynasty.",
    iconName: "badge-dynasty-member",
    progressKind: "counter",
    counterOf: { stat: "yearsActive", target: 5, label: "Years active" },
    triggerSources: ["attendance"]
  },
  {
    id: "digital-triple-crown",
    kind: "Badge",
    name: "The Digital Triple Crown",
    tier: "HallOfFamer",
    category: "TrainingProgram",
    description: "Completed all Foundation program videos: 36 Skills + 12 S&C + 12 IQ.",
    iconName: "badge-digital-crown",
    progressKind: "completeAll",
    completeAll: { setId: "foundation_all", label: "All Foundation videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "foundation-alumnus",
    kind: "Badge",
    name: "Foundation Alumnus",
    tier: "HallOfFamer",
    category: "TrainingProgram",
    description: "Completed the 12-week Foundation program twice - true dedication to improvement.",
    iconName: "badge-foundation-alumnus",
    progressKind: "counter",
    counterOf: { stat: "foundation.completedTwice", target: 1, label: "Times completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },

  // ===== BADGES - SUPERSTAR (Purple) =====
  
  {
    id: "marquee-player",
    kind: "Badge",
    name: "Marquee Player",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 MVP awards - a recognized star performer.",
    iconName: "badge-marquee-player",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 5, label: "MVP awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "ice-in-veins",
    kind: "Badge",
    name: "Ice in the Veins",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Clutch awards - performs best under pressure.",
    iconName: "badge-ice-veins",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 5, label: "Clutch awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "momentum-shifter",
    kind: "Badge",
    name: "Momentum Shifter",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Comeback awards - turns the tide when it matters.",
    iconName: "badge-momentum-shifter",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 5, label: "Comeback awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-workhorse",
    kind: "Badge",
    name: "The Workhorse",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Hustle awards - elite work ethic.",
    iconName: "badge-workhorse",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 5, label: "Hustle awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-cornerstone",
    kind: "Badge",
    name: "The Cornerstone",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Teammate awards - foundation of team unity.",
    iconName: "badge-cornerstone",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 5, label: "Teammate awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-ambassador",
    kind: "Badge",
    name: "The Ambassador",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Sportsmanship awards - represents the best of basketball.",
    iconName: "badge-ambassador",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 5, label: "Sportsmanship awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-tactician",
    kind: "Badge",
    name: "The Tactician",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Student awards - master of basketball strategy.",
    iconName: "badge-tactician",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 5, label: "Student awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-blueprint",
    kind: "Badge",
    name: "The Blueprint",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "Earned 5 Lead by Example awards - the model others follow.",
    iconName: "badge-blueprint",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 5, label: "Lead by Example awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-pillar",
    kind: "Badge",
    name: "The Pillar",
    tier: "Superstar",
    category: "Attendance",
    description: "Attended every practice in a season - unwavering commitment.",
    iconName: "badge-pillar",
    progressKind: "composite",
    composite: [{ stat: "playedEveryPracticeSeason", min: 1 }],
    triggerSources: ["attendance", "rsvp"]
  },
  {
    id: "ironman",
    kind: "Badge",
    name: "Ironman",
    tier: "Superstar",
    category: "Attendance",
    description: "Played in every game in a season - ultimate durability.",
    iconName: "badge-ironman",
    progressKind: "composite",
    composite: [{ stat: "playedEveryGameSeason", min: 1 }],
    triggerSources: ["attendance", "rsvp"]
  },
  {
    id: "fnhironman",
    kind: "Badge",
    name: "FNH Ironman",
    tier: "Superstar",
    category: "Attendance",
    description: "Played in every FNH game in a season - Friday night warrior.",
    iconName: "badge-fnh-ironman",
    progressKind: "composite",
    composite: [{ stat: "playedEveryFnhSeason", min: 1 }],
    triggerSources: ["attendance", "rsvp"]
  },
  {
    id: "practice-centurion",
    kind: "Badge",
    name: "Practice Centurion",
    tier: "Superstar",
    category: "Attendance",
    description: "Attended 100 total practices - century of dedication.",
    iconName: "badge-practice-centurion",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 100, label: "Practices attended" },
    triggerSources: ["attendance"]
  },
  {
    id: "skills-specialist",
    kind: "Badge",
    name: "Skills Specialist",
    tier: "Superstar",
    category: "Attendance",
    description: "Attended 100 skills sessions - specialist in improvement.",
    iconName: "badge-skills-specialist",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 100, label: "Skills sessions attended" },
    triggerSources: ["attendance"]
  },
  {
    id: "century-club",
    kind: "Badge",
    name: "Century Club",
    tier: "Superstar",
    category: "Attendance",
    description: "Played in 100 games - member of the century club.",
    iconName: "badge-century-club",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 100, label: "Games played" },
    triggerSources: ["attendance"]
  },
  {
    id: "fnhlegend",
    kind: "Badge",
    name: "FNH Legend",
    tier: "Superstar",
    category: "Attendance",
    description: "Played in 100 FNH games - Friday night legend.",
    iconName: "badge-fnh-legend",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 100, label: "FNH games played" },
    triggerSources: ["attendance"]
  },
  {
    id: "team-veteran",
    kind: "Badge",
    name: "Team Veteran",
    tier: "Superstar",
    category: "Attendance",
    description: "Active member for 3 years - seasoned veteran.",
    iconName: "badge-team-veteran",
    progressKind: "counter",
    counterOf: { stat: "yearsActive", target: 3, label: "Years active" },
    triggerSources: ["attendance"]
  },
  {
    id: "foundation-graduate",
    kind: "Badge",
    name: "Foundation Graduate",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Completed all 60 Foundation videos over 12 weeks - full program graduate.",
    iconName: "badge-foundation-graduate",
    progressKind: "counter",
    counterOf: { stat: "foundation.totalVideos", target: 60, label: "Videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "technique-titan",
    kind: "Badge",
    name: "Technique Titan",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Completed all 36 Skills videos - master of technique.",
    iconName: "badge-technique-titan",
    progressKind: "counter",
    counterOf: { stat: "foundation.skillsCompleted", target: 36, label: "Skills videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "peak-performer",
    kind: "Badge",
    name: "Peak Performer",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Completed all 12 S&C videos - peak physical conditioning.",
    iconName: "badge-peak-performer",
    progressKind: "counter",
    counterOf: { stat: "foundation.scCompleted", target: 12, label: "S&C videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "basketball-savant",
    kind: "Badge",
    name: "Basketball Savant",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Completed all 12 IQ videos - basketball genius.",
    iconName: "badge-basketball-savant",
    progressKind: "counter",
    counterOf: { stat: "foundation.iqCompleted", target: 12, label: "IQ videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "perfect-attendance-online",
    kind: "Badge",
    name: "Perfect Attendance: Online",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "Completed 12 consecutive weeks of Foundation training - perfect online attendance.",
    iconName: "badge-perfect-attendance-online",
    progressKind: "counter",
    counterOf: { stat: "foundation.weeklyCompleted12", target: 1, label: "12-week streak" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },

  // ===== BADGES - ALL-STAR (Blue) =====
  
  {
    id: "game-changer",
    kind: "Badge",
    name: "Game Changer",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 MVP awards - consistently makes a pivotal impact.",
    iconName: "badge-game-changer",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 3, label: "MVP awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-closer",
    kind: "Badge",
    name: "The Closer",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Clutch awards - finishes games when it counts.",
    iconName: "badge-closer",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 3, label: "Clutch awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-sparkplug",
    kind: "Badge",
    name: "The Sparkplug",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Comeback awards - ignites the team's comeback efforts.",
    iconName: "badge-sparkplug",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 3, label: "Comeback awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-engine",
    kind: "Badge",
    name: "The Engine",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Hustle awards - consistent source of energy.",
    iconName: "badge-engine",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 3, label: "Hustle awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-glue",
    kind: "Badge",
    name: "The Glue",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Teammate awards - positive and unifying presence.",
    iconName: "badge-glue",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 3, label: "Teammate awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "class-act",
    kind: "Badge",
    name: "Class Act",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Sportsmanship awards - exemplifies class and respect.",
    iconName: "badge-class-act",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 3, label: "Sportsmanship awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-protege",
    kind: "Badge",
    name: "The Protégé",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Student awards - eager learner with high basketball IQ.",
    iconName: "badge-protege",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 3, label: "Student awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-standard",
    kind: "Badge",
    name: "The Standard",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "Earned 3 Lead by Example awards - sets the standard for others.",
    iconName: "badge-standard",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 3, label: "Lead by Example awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "the-dependable",
    kind: "Badge",
    name: "The Dependable",
    tier: "AllStar",
    category: "Attendance",
    description: "RSVPed to every event in a season - absolutely dependable.",
    iconName: "badge-dependable",
    progressKind: "composite",
    composite: [{ stat: "rsvpedEveryEventSeason", min: 1 }],
    triggerSources: ["rsvp"]
  },
  {
    id: "recruiter",
    kind: "Badge",
    name: "Recruiter",
    tier: "AllStar",
    category: "Attendance",
    description: "Referred a new player who joined - grows the UYP family.",
    iconName: "badge-recruiter",
    progressKind: "counter",
    counterOf: { stat: "referrals", target: 1, label: "Player referrals" },
    triggerSources: ["coachAward"]
  },
  {
    id: "practice-fiend",
    kind: "Badge",
    name: "Practice Fiend",
    tier: "AllStar",
    category: "Attendance",
    description: "Attended 50 total practices - dedicated to improvement.",
    iconName: "badge-practice-fiend",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 50, label: "Practices attended" },
    triggerSources: ["attendance"]
  },
  {
    id: "skills-devotee",
    kind: "Badge",
    name: "Skills Devotee",
    tier: "AllStar",
    category: "Attendance",
    description: "Attended 50 skills sessions - devoted to skill development.",
    iconName: "badge-skills-devotee",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 50, label: "Skills sessions attended" },
    triggerSources: ["attendance"]
  },
  {
    id: "seasoned-competitor",
    kind: "Badge",
    name: "Seasoned Competitor",
    tier: "AllStar",
    category: "Attendance",
    description: "Played in 50 games - seasoned game experience.",
    iconName: "badge-seasoned-competitor",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 50, label: "Games played" },
    triggerSources: ["attendance"]
  },
  {
    id: "fnhveteran",
    kind: "Badge",
    name: "FNH Veteran",
    tier: "AllStar",
    category: "Attendance",
    description: "Played in 50 FNH games - Friday night veteran.",
    iconName: "badge-fnh-veteran",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 50, label: "FNH games played" },
    triggerSources: ["attendance"]
  },
  {
    id: "first-year-anniversary",
    kind: "Badge",
    name: "First Year Anniversary",
    tier: "AllStar",
    category: "Attendance",
    description: "Completed first year with UYP - foundation established.",
    iconName: "badge-first-year",
    progressKind: "counter",
    counterOf: { stat: "yearsActive", target: 1, label: "Years active" },
    triggerSources: ["attendance"]
  },
  {
    id: "half-time-adjustments",
    kind: "Badge",
    name: "Half-Time Adjustments",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Completed 30 Foundation videos - making progress like half-time adjustments.",
    iconName: "badge-half-time",
    progressKind: "counter",
    counterOf: { stat: "foundation.totalVideos", target: 30, label: "Videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "monthly-module-master",
    kind: "Badge",
    name: "Monthly Module Master",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Completed 4 consecutive weeks of training - monthly consistency.",
    iconName: "badge-monthly-master",
    progressKind: "counter",
    counterOf: { stat: "foundation.monthly4", target: 1, label: "4 weeks in a row" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "skills-sharp-shooter",
    kind: "Badge",
    name: "Skills Sharp-Shooter",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Completed 20 Skills videos - sharp shooting technique.",
    iconName: "badge-skills-sharp",
    progressKind: "counter",
    counterOf: { stat: "foundation.skillsCompleted", target: 20, label: "Skills videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "conditioning-core",
    kind: "Badge",
    name: "Conditioning Core",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Completed 6 S&C videos - building core conditioning.",
    iconName: "badge-conditioning-core",
    progressKind: "counter",
    counterOf: { stat: "foundation.scCompleted", target: 6, label: "S&C videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "strategic-specialist",
    kind: "Badge",
    name: "Strategic Specialist",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Completed 6 IQ videos - developing strategic understanding.",
    iconName: "badge-strategic-specialist",
    progressKind: "counter",
    counterOf: { stat: "foundation.iqCompleted", target: 6, label: "IQ videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "mid-season-mentor",
    kind: "Badge",
    name: "Mid-Season Mentor",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "Completed 6 consecutive weeks of training - mid-season consistency.",
    iconName: "badge-mid-season",
    progressKind: "counter",
    counterOf: { stat: "foundation.weeklyCompleted6", target: 1, label: "6-week streak" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },

  // ===== BADGES - STARTER (Green) =====
  
  {
    id: "locked-in",
    kind: "Badge",
    name: "Locked In",
    tier: "Starter",
    category: "Attendance",
    description: "Attended 10 consecutive practices - completely locked in.",
    iconName: "badge-locked-in",
    progressKind: "streak",
    streakOf: { stat: "practiceStreak", target: 10, label: "Practice streak" },
    triggerSources: ["attendance"]
  },
  {
    id: "on-the-ball",
    kind: "Badge",
    name: "On the Ball",
    tier: "Starter",
    category: "Attendance",
    description: "Made 10 consecutive on-time RSVPs - always on the ball.",
    iconName: "badge-on-ball",
    progressKind: "streak",
    streakOf: { stat: "rsvpStreak", target: 10, label: "RSVP streak" },
    triggerSources: ["rsvp"]
  },
  {
    id: "tournament-titan",
    kind: "Badge",
    name: "Tournament Titan",
    tier: "Starter",
    category: "Attendance",
    description: "Checked into all games in a tournament - tournament warrior.",
    iconName: "badge-tournament-titan",
    progressKind: "composite",
    composite: [{ stat: "tournamentAllGamesCheckedIn", min: 1 }],
    triggerSources: ["attendance"]
  },
  {
    id: "dedicated-grinder",
    kind: "Badge",
    name: "Dedicated Grinder",
    tier: "Starter",
    category: "Attendance",
    description: "Attended 25 practices - dedicated to the grind.",
    iconName: "badge-dedicated-grinder",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 25, label: "Practices attended" },
    triggerSources: ["attendance"]
  },
  {
    id: "skills-seeker",
    kind: "Badge",
    name: "Skills Seeker",
    tier: "Starter",
    category: "Attendance",
    description: "Attended 25 skills sessions - always seeking improvement.",
    iconName: "badge-skills-seeker",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 25, label: "Skills sessions attended" },
    triggerSources: ["attendance"]
  },
  {
    id: "regular-competitor",
    kind: "Badge",
    name: "Regular Competitor",
    tier: "Starter",
    category: "Attendance",
    description: "Played in 25 games - regular competitor.",
    iconName: "badge-regular-competitor",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 25, label: "Games played" },
    triggerSources: ["attendance"]
  },
  {
    id: "fnhregular",
    kind: "Badge",
    name: "FNH Regular",
    tier: "Starter",
    category: "Attendance",
    description: "Played in 25 FNH games - Friday night regular.",
    iconName: "badge-fnh-regular",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 25, label: "FNH games played" },
    triggerSources: ["attendance"]
  },
  {
    id: "game-mvp",
    kind: "Badge",
    name: "Game MVP",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned first MVP award - instrumental game performance.",
    iconName: "badge-game-mvp",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 1, label: "MVP awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "clutch-player",
    kind: "Badge",
    name: "Clutch Player",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned first Clutch award - made a game-changing play under pressure.",
    iconName: "badge-clutch-player",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 1, label: "Clutch awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "comeback-kid",
    kind: "Badge",
    name: "Comeback Kid",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned first Comeback award - helped turn the game around.",
    iconName: "badge-comeback-kid",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 1, label: "Comeback awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "sportsmanship-award",
    kind: "Badge",
    name: "Sportsmanship Award",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned first Sportsmanship award - displays excellent sportsmanship.",
    iconName: "badge-sportsmanship",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 1, label: "Sportsmanship awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "hustle-award",
    kind: "Badge",
    name: "Hustle Award",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned first Hustle award - relentless hustle and effort.",
    iconName: "badge-hustle-award",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 1, label: "Hustle awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "teammate-award",
    kind: "Badge",
    name: "Teammate Award",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned first Teammate award - encouraging, supportive, or unselfish play.",
    iconName: "badge-teammate-award",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 1, label: "Teammate awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "student-of-game",
    kind: "Badge",
    name: "Student of the Game",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned first Student award - exceptional listening skills and attentiveness.",
    iconName: "badge-student-game",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 1, label: "Student awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "lead-by-example",
    kind: "Badge",
    name: "Lead by Example",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Earned first Lead by Example award - flawlessly demonstrating skills.",
    iconName: "badge-lead-example",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 1, label: "Lead by Example awards" },
    triggerSources: ["coachAward"]
  },
  {
    id: "weekly-warm-up",
    kind: "Badge",
    name: "Weekly Warm-Up",
    tier: "Starter",
    category: "TrainingProgram",
    description: "Completed all 5 videos in one week - full weekly commitment.",
    iconName: "badge-weekly-warmup",
    progressKind: "counter",
    counterOf: { stat: "foundation.weeklyCompleted1", target: 1, label: "One full week" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "film-study",
    kind: "Badge",
    name: "Film Study",
    tier: "Starter",
    category: "TrainingProgram",
    description: "Completed 10 total Foundation videos - dedicated to film study.",
    iconName: "badge-film-study",
    progressKind: "counter",
    counterOf: { stat: "foundation.totalVideos", target: 10, label: "Videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "skill-builder",
    kind: "Badge",
    name: "Skill Builder",
    tier: "Starter",
    category: "TrainingProgram",
    description: "Completed 5 Skills videos - building fundamental skills.",
    iconName: "badge-skill-builder",
    progressKind: "counter",
    counterOf: { stat: "foundation.skillsCompleted", target: 5, label: "Skills videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "foundation-force",
    kind: "Badge",
    name: "Foundation Force",
    tier: "Starter",
    category: "TrainingProgram",
    description: "Completed 5 S&C videos - building foundation strength.",
    iconName: "badge-foundation-force",
    progressKind: "counter",
    counterOf: { stat: "foundation.scCompleted", target: 5, label: "S&C videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "court-visionary",
    kind: "Badge",
    name: "Court Visionary",
    tier: "Starter",
    category: "TrainingProgram",
    description: "Completed 5 IQ videos - developing court vision.",
    iconName: "badge-court-visionary",
    progressKind: "counter",
    counterOf: { stat: "foundation.iqCompleted", target: 5, label: "IQ videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "back-to-back-sessions",
    kind: "Badge",
    name: "Back-to-Back Sessions",
    tier: "Starter",
    category: "TrainingProgram",
    description: "Completed two consecutive weeks of training - building momentum.",
    iconName: "badge-back-to-back",
    progressKind: "counter",
    counterOf: { stat: "foundation.weeklyCompleted2", target: 1, label: "2-week streak" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },

  // ===== BADGES - PROSPECT (Grey) =====
  
  {
    id: "checked-in",
    kind: "Badge",
    name: "Checked In",
    tier: "Prospect",
    category: "Attendance",
    description: "Checked into any UYP event - welcome to the family!",
    iconName: "badge-checked-in",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 1, label: "Events attended" },
    triggerSources: ["attendance"]
  },
  {
    id: "road-warrior",
    kind: "Badge",
    name: "Road Warrior",
    tier: "Prospect",
    category: "Attendance",
    description: "Checked in at a different location - willing to travel for basketball.",
    iconName: "badge-road-warrior",
    progressKind: "counter",
    counterOf: { stat: "distinctLocations", target: 2, label: "Different locations" },
    triggerSources: ["attendance"]
  },
  {
    id: "holiday-hero",
    kind: "Badge",
    name: "Holiday Hero",
    tier: "Prospect",
    category: "Attendance",
    description: "Played on a major holiday - dedicated even during holidays.",
    iconName: "badge-holiday-hero",
    progressKind: "counter",
    counterOf: { stat: "holidayGamesCount", target: 1, label: "Holiday games" },
    triggerSources: ["attendance"]
  },
  {
    id: "the-debut",
    kind: "Badge",
    name: "The Debut",
    tier: "Prospect",
    category: "Attendance",
    description: "Played in your very first game - the beginning of your journey.",
    iconName: "badge-debut",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 1, label: "Games played" },
    triggerSources: ["attendance"]
  },
  {
    id: "friday-follower",
    kind: "Badge",
    name: "Friday Follower",
    tier: "Prospect",
    category: "Attendance",
    description: "Played in your first Friday Night Hoops game - welcome to FNH!",
    iconName: "badge-friday-follower",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 1, label: "FNH games" },
    triggerSources: ["attendance"]
  },
  {
    id: "heating-up",
    kind: "Badge",
    name: "Heating Up",
    tier: "Prospect",
    category: "Attendance",
    description: "Attended 5 consecutive practices - starting to heat up!",
    iconName: "badge-heating-up",
    progressKind: "streak",
    streakOf: { stat: "practiceStreak", target: 5, label: "Practice streak" },
    triggerSources: ["attendance"]
  },
  {
    id: "game-planner",
    kind: "Badge",
    name: "Game Planner",
    tier: "Prospect",
    category: "Attendance",
    description: "RSVPed to a game within the proper window - good planning!",
    iconName: "badge-game-planner",
    progressKind: "counter",
    counterOf: { stat: "rsvpsOnTimeSeason", target: 1, label: "On-time RSVPs" },
    triggerSources: ["rsvp"]
  },
  {
    id: "practice-planner",
    kind: "Badge",
    name: "Practice Planner",
    tier: "Prospect",
    category: "Attendance",
    description: "RSVPed to a Practice, Skill, or FNH event - planning ahead!",
    iconName: "badge-practice-planner",
    progressKind: "counter",
    counterOf: { stat: "rsvpsOnTimeSeason", target: 1, label: "On-time RSVPs" },
    triggerSources: ["rsvp"]
  },
  {
    id: "first-reps",
    kind: "Badge",
    name: "First Reps",
    tier: "Prospect",
    category: "Attendance",
    description: "Attended 10 total practices - getting your first reps in.",
    iconName: "badge-first-reps",
    progressKind: "counter",
    counterOf: { stat: "practiceTotal", target: 10, label: "Practices attended" },
    triggerSources: ["attendance"]
  },
  {
    id: "skill-starter",
    kind: "Badge",
    name: "Skill Starter",
    tier: "Prospect",
    category: "Attendance",
    description: "Attended 10 skills sessions - starting your skill development.",
    iconName: "badge-skill-starter",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 10, label: "Skills sessions attended" },
    triggerSources: ["attendance"]
  },
  {
    id: "first-ten",
    kind: "Badge",
    name: "First Ten",
    tier: "Prospect",
    category: "Attendance",
    description: "Played in 10 total games - first ten games under your belt.",
    iconName: "badge-first-ten",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 10, label: "Games played" },
    triggerSources: ["attendance"]
  },
  {
    id: "fnhfighter",
    kind: "Badge",
    name: "FNH Fighter",
    tier: "Prospect",
    category: "Attendance",
    description: "Played in 10 total FNH games - Friday night fighter spirit.",
    iconName: "badge-fnh-fighter",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 10, label: "FNH games played" },
    triggerSources: ["attendance"]
  },
  {
    id: "digital-first-steps",
    kind: "Badge",
    name: "Digital First Steps",
    tier: "Prospect",
    category: "TrainingProgram",
    description: "Completed your first Foundation program video - taking digital first steps.",
    iconName: "badge-digital-first",
    progressKind: "counter",
    counterOf: { stat: "foundation.totalVideos", target: 1, label: "Videos completed" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "virtual-handles",
    kind: "Badge",
    name: "Virtual Handles",
    tier: "Prospect",
    category: "TrainingProgram",
    description: "Completed your first Skills video - working on virtual handles.",
    iconName: "badge-virtual-handles",
    progressKind: "counter",
    counterOf: { stat: "foundation.skillsCompleted", target: 1, label: "Skills videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "remote-strength",
    kind: "Badge",
    name: "Remote Strength",
    tier: "Prospect",
    category: "TrainingProgram",
    description: "Completed your first S&C video - building remote strength.",
    iconName: "badge-remote-strength",
    progressKind: "counter",
    counterOf: { stat: "foundation.scCompleted", target: 1, label: "S&C videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  },
  {
    id: "mindful-start",
    kind: "Badge",
    name: "Mindful Start",
    tier: "Prospect",
    category: "TrainingProgram",
    description: "Completed your first IQ video - making a mindful start to basketball education.",
    iconName: "badge-mindful-start",
    progressKind: "counter",
    counterOf: { stat: "foundation.iqCompleted", target: 1, label: "IQ videos" },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"]
  }
];

// Helper functions for filtering and sorting
export const TIER_COLORS = {
  HallOfFamer: { bg: "bg-yellow-500", text: "text-yellow-600", border: "border-yellow-500", name: "Hall of Famer" },
  Superstar: { bg: "bg-purple-500", text: "text-purple-600", border: "border-purple-500", name: "Superstar" },
  AllStar: { bg: "bg-blue-500", text: "text-blue-600", border: "border-blue-500", name: "All-Star" },
  Starter: { bg: "bg-green-500", text: "text-green-600", border: "border-green-500", name: "Starter" },
  Prospect: { bg: "bg-gray-500", text: "text-gray-600", border: "border-gray-500", name: "Prospect" },
  Legacy: { bg: "bg-gradient-to-r from-yellow-400 to-yellow-600", text: "text-yellow-700", border: "border-yellow-500", name: "Legacy" },
  Team: { bg: "bg-gradient-to-r from-orange-400 to-orange-600", text: "text-orange-700", border: "border-orange-500", name: "Team" }
};

export const TIER_ORDER = ["Legacy", "Team", "HallOfFamer", "Superstar", "AllStar", "Starter", "Prospect"];
