import type { LucideIcon } from "lucide-react";
import {
  Trophy,
  Medal,
  Star,
  Flame,
  Zap,
  Target,
  Shield,
  Crown,
  Sword,
  Dumbbell,
  Timer,
  Heart,
  ThumbsUp,
  Award,
  Gem,
  Mountain,
  Sunrise,
  Rocket,
  CircleCheck,
  TrendingUp,
  BarChart,
  Activity,
  Swords,
  Footprints,
  Wind,
  Sparkles,
  Hexagon,
  Diamond,
  Bike,
  Waves,
  Snowflake,
  Sun,
  Moon,
  Globe,
  Map,
  Compass,
  Flag,
  FlagTriangleRight,
  Cpu,
  Crosshair,
  Eye,
  Layers,
  Lock,
  Unlock,
  Users,
  UserCheck,
  Coffee,
  Brain,
  AlarmClock,
  CalendarCheck,
  CalendarDays,
  Clock,
  Hourglass,
  RefreshCw,
  Repeat,
  ArrowUp,
  ArrowUpRight,
  ChevronsUp,
  PlusCircle,
  Octagon,
  Laugh,
  Smile,
  Salad,
  Apple,
  Banana,
  Feather,
  Leaf,
  TreePine,
  Trees,
  Flower,
  Flower2,
  Bird,
  Fish,
  Turtle,
  Route,
  Milestone,
  Focus,
  Radar,
  Signal,
  Satellite,
  ShieldCheck,
  BadgeCheck,
  BadgePlus,
  Ribbon,
  Gift,
  Package,
  Box,
  Volleyball,
  HeartHandshake,
  Handshake,
  Lightbulb,
  BicepsFlexed,
  Gamepad2,
  Watch,
  Music,
  Wifi,
  Radio,
  BrainCircuit,
  FlaskConical,
  PersonStanding,
} from "lucide-react";

export interface AwardIcon {
  id: string;
  label: string;
  component: LucideIcon;
  category: "achievement" | "sports" | "fitness" | "nature" | "misc";
}

export const AWARD_ICONS: AwardIcon[] = [
  { id: "trophy", label: "Trophy", component: Trophy, category: "achievement" },
  { id: "medal", label: "Medal", component: Medal, category: "achievement" },
  { id: "star", label: "Star", component: Star, category: "achievement" },
  { id: "crown", label: "Crown", component: Crown, category: "achievement" },
  { id: "award", label: "Award", component: Award, category: "achievement" },
  { id: "gem", label: "Gem", component: Gem, category: "achievement" },
  { id: "diamond", label: "Diamond", component: Diamond, category: "achievement" },
  { id: "shield-check", label: "Shield Check", component: ShieldCheck, category: "achievement" },
  { id: "badge-check", label: "Badge Check", component: BadgeCheck, category: "achievement" },
  { id: "badge-plus", label: "Badge Plus", component: BadgePlus, category: "achievement" },
  { id: "ribbon", label: "Ribbon", component: Ribbon, category: "achievement" },
  { id: "circle-check", label: "Circle Check", component: CircleCheck, category: "achievement" },
  { id: "gift", label: "Gift", component: Gift, category: "achievement" },
  { id: "sparkles", label: "Sparkles", component: Sparkles, category: "achievement" },
  { id: "hexagon", label: "Hexagon", component: Hexagon, category: "achievement" },
  { id: "octagon", label: "Octagon", component: Octagon, category: "achievement" },
  { id: "flame", label: "Flame", component: Flame, category: "sports" },
  { id: "zap", label: "Lightning", component: Zap, category: "sports" },
  { id: "target", label: "Target", component: Target, category: "sports" },
  { id: "crosshair", label: "Crosshair", component: Crosshair, category: "sports" },
  { id: "sword", label: "Sword", component: Sword, category: "sports" },
  { id: "swords", label: "Swords", component: Swords, category: "sports" },
  { id: "shield", label: "Shield", component: Shield, category: "sports" },
  { id: "flag", label: "Flag", component: Flag, category: "sports" },
  { id: "flag-triangle", label: "Race Flag", component: FlagTriangleRight, category: "sports" },
  { id: "volleyball", label: "Ball", component: Volleyball, category: "sports" },
  { id: "bike", label: "Bike", component: Bike, category: "sports" },
  { id: "waves", label: "Waves", component: Waves, category: "sports" },
  { id: "dumbbell", label: "Dumbbell", component: Dumbbell, category: "fitness" },
  { id: "heart", label: "Heart", component: Heart, category: "fitness" },
  { id: "activity", label: "Activity", component: Activity, category: "fitness" },
  { id: "trending-up", label: "Trending Up", component: TrendingUp, category: "fitness" },
  { id: "bar-chart", label: "Bar Chart", component: BarChart, category: "fitness" },
  { id: "timer", label: "Timer", component: Timer, category: "fitness" },
  { id: "hourglass", label: "Hourglass", component: Hourglass, category: "fitness" },
  { id: "clock", label: "Clock", component: Clock, category: "fitness" },
  { id: "alarm-clock", label: "Alarm Clock", component: AlarmClock, category: "fitness" },
  { id: "calendar-check", label: "Calendar Check", component: CalendarCheck, category: "fitness" },
  { id: "calendar-days", label: "Calendar Days", component: CalendarDays, category: "fitness" },
  { id: "repeat", label: "Repeat", component: Repeat, category: "fitness" },
  { id: "refresh-cw", label: "Refresh", component: RefreshCw, category: "fitness" },
  { id: "footprints", label: "Footprints", component: Footprints, category: "fitness" },
  { id: "route", label: "Route", component: Route, category: "fitness" },
  { id: "milestone", label: "Milestone", component: Milestone, category: "fitness" },
  { id: "wind", label: "Wind", component: Wind, category: "fitness" },
  { id: "mountain", label: "Mountain", component: Mountain, category: "nature" },
  { id: "sunrise", label: "Sunrise", component: Sunrise, category: "nature" },
  { id: "sun", label: "Sun", component: Sun, category: "nature" },
  { id: "moon", label: "Moon", component: Moon, category: "nature" },
  { id: "snowflake", label: "Snowflake", component: Snowflake, category: "nature" },
  { id: "leaf", label: "Leaf", component: Leaf, category: "nature" },
  { id: "tree-pine", label: "Pine Tree", component: TreePine, category: "nature" },
  { id: "trees", label: "Trees", component: Trees, category: "nature" },
  { id: "flower", label: "Flower", component: Flower, category: "nature" },
  { id: "flower2", label: "Flower 2", component: Flower2, category: "nature" },
  { id: "bird", label: "Bird", component: Bird, category: "nature" },
  { id: "feather", label: "Feather", component: Feather, category: "nature" },
  { id: "fish", label: "Fish", component: Fish, category: "nature" },
  { id: "turtle", label: "Turtle", component: Turtle, category: "nature" },
  { id: "banana", label: "Banana", component: Banana, category: "nature" },
  { id: "thumbs-up", label: "Thumbs Up", component: ThumbsUp, category: "misc" },
  { id: "arrow-up", label: "Arrow Up", component: ArrowUp, category: "misc" },
  { id: "arrow-up-right", label: "Arrow Up-Right", component: ArrowUpRight, category: "misc" },
  { id: "chevrons-up", label: "Chevrons Up", component: ChevronsUp, category: "misc" },
  { id: "users", label: "Team", component: Users, category: "misc" },
  { id: "user-check", label: "Player Check", component: UserCheck, category: "misc" },
  { id: "eye", label: "Eye", component: Eye, category: "misc" },
  { id: "focus", label: "Focus", component: Focus, category: "misc" },
  { id: "radar", label: "Radar", component: Radar, category: "misc" },
  { id: "compass", label: "Compass", component: Compass, category: "misc" },
  { id: "globe", label: "Globe", component: Globe, category: "misc" },
  { id: "map", label: "Map", component: Map, category: "misc" },
  { id: "brain", label: "Brain", component: Brain, category: "misc" },
  { id: "cpu", label: "Chip", component: Cpu, category: "misc" },
  { id: "layers", label: "Layers", component: Layers, category: "misc" },
  { id: "signal", label: "Signal", component: Signal, category: "misc" },
  { id: "satellite", label: "Satellite", component: Satellite, category: "misc" },
  { id: "coffee", label: "Coffee", component: Coffee, category: "misc" },
  { id: "smile", label: "Smile", component: Smile, category: "misc" },
  { id: "laugh", label: "Laugh", component: Laugh, category: "misc" },
  { id: "apple", label: "Apple", component: Apple, category: "misc" },
  { id: "salad", label: "Salad", component: Salad, category: "misc" },
  { id: "plus-circle", label: "Plus Circle", component: PlusCircle, category: "misc" },
  { id: "lock", label: "Lock", component: Lock, category: "misc" },
  { id: "unlock", label: "Unlock", component: Unlock, category: "misc" },
  { id: "package", label: "Package", component: Package, category: "misc" },
  { id: "box", label: "Box", component: Box, category: "misc" },
  { id: "rocket", label: "Rocket", component: Rocket, category: "misc" },
  { id: "heart-handshake", label: "Sportsmanship", component: HeartHandshake, category: "achievement" },
  { id: "handshake", label: "Teamwork", component: Handshake, category: "achievement" },
  { id: "lightbulb", label: "Lightbulb", component: Lightbulb, category: "misc" },
  { id: "biceps-flexed", label: "Strength", component: BicepsFlexed, category: "fitness" },
  { id: "gamepad2", label: "Gamepad", component: Gamepad2, category: "sports" },
  { id: "watch", label: "Watch", component: Watch, category: "fitness" },
  { id: "music", label: "Music", component: Music, category: "misc" },
  { id: "wifi", label: "Wifi", component: Wifi, category: "misc" },
  { id: "radio", label: "Radio", component: Radio, category: "misc" },
  { id: "brain-circuit", label: "Smart Play", component: BrainCircuit, category: "misc" },
  { id: "flask-conical", label: "Science", component: FlaskConical, category: "misc" },
  { id: "person-standing", label: "Player", component: PersonStanding, category: "sports" },
];

export const AWARD_ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  AWARD_ICONS.map((icon) => [icon.id, icon.component])
);

export function getAwardIcon(identifier: string | null | undefined): LucideIcon | null {
  if (!identifier) return null;
  return AWARD_ICON_MAP[identifier] || null;
}

export function isIconIdentifier(value: string | null | undefined): boolean {
  if (!value) return false;
  return value in AWARD_ICON_MAP;
}
