import { db } from "./db";
import { badges, trophies } from "@shared/schema";

// Comprehensive badge and trophy seed data based on UYP Basketball achievement system

export const seedBadgesAndTrophies = async () => {
  console.log("🏆 Seeding badges and trophies...");

  try {
    console.log("  ℹ️  Using upsert to preserve existing badge/trophy references");

    // === TROPHIES ===
    const trophyData = [
      // UYP Legacy Trophies (Yearly - Org-wide)
      {
        name: "The UYP Heart and Hustle Award",
        slug: "uyp-heart-and-hustle",
        description: "This yearly award recognizes the single player in all of UYP who most consistently gave their all, demonstrating exceptional effort and determination in every practice and game.",
        icon: "/trophies/uyp-heart-and-hustle.png",
        type: "legacy" as const,
        criteria: { type: "coach_nomination", scope: "org-wide", frequency: "yearly" },
      },
      {
        name: "The Spirit Award",
        slug: "spirit-award",
        description: "Awarded to the one player across the entire organization who best maintained a positive attitude, lifted team morale, and represented the character of UYP both on and off the court.",
        icon: "/trophies/spirit-award.png",
        type: "legacy" as const,
        criteria: { type: "coach_nomination", scope: "org-wide", frequency: "yearly" },
      },
      
      // Team Trophies (Seasonal - Coach-awarded)
      {
        name: "MVP (Most Valuable Player)",
        slug: "mvp",
        description: "Awarded to the player who had the most significant impact on the team's success during the season.",
        icon: "/trophies/mvp.png",
        type: "team" as const,
        criteria: { type: "coach_award", scope: "team", frequency: "seasonal" },
      },
      {
        name: "Coach's Award",
        slug: "coaches-award",
        description: "Given to the player who best exemplifies the team's core values and the coach's philosophy, demonstrating coachability, dedication, and a positive attitude throughout the season.",
        icon: "/trophies/coaches-award.png",
        type: "team" as const,
        criteria: { type: "coach_award", scope: "team", frequency: "seasonal" },
      },
      {
        name: "MIP (Most Improved Player)",
        slug: "mip",
        description: "Awarded to the player who has shown the most significant growth and development in their skills and game sense over the course of the season.",
        icon: "/trophies/mip.png",
        type: "team" as const,
        criteria: { type: "coach_award", scope: "team", frequency: "seasonal" },
      },
      {
        name: "Defensive Player",
        slug: "defensive-player",
        description: "Awarded to the player that has had the greatest defensive impact during the season.",
        icon: "/trophies/defensive-player.png",
        type: "team" as const,
        criteria: { type: "coach_award", scope: "team", frequency: "seasonal" },
      },
    ];

    // Upsert trophies (insert or update based on slug)
    for (const trophy of trophyData) {
      await db.insert(trophies)
        .values(trophy)
        .onConflictDoUpdate({
          target: trophies.slug,
          set: trophy,
        });
    }
    console.log(`  ✓ Seeded ${trophyData.length} trophies`);

    // === BADGES ===
    
    // Hall of Fame (Gold) – Legends Only
    const hallOfFameBadges = [
      {
        name: "Superstar Supreme",
        slug: "superstar-supreme",
        description: "10× MVPs",
        icon: "/badges/superstar-supreme.png",
        color: "#FFD700",
        tier: "hall-of-fame" as const,
        category: "awards",
        type: "mvp-milestone",
        criteria: { requirement: "10 MVP awards" },
      },
      {
        name: "Relentless",
        slug: "relentless",
        description: "10× Hustle",
        icon: "/badges/relentless.png",
        color: "#FFD700",
        tier: "hall-of-fame" as const,
        category: "awards",
        type: "hustle-milestone",
        criteria: { requirement: "10 Hustle awards" },
      },
      {
        name: "The Linchpin",
        slug: "the-linchpin",
        description: "10× Teammate",
        icon: "/badges/the-linchpin.png",
        color: "#FFD700",
        tier: "hall-of-fame" as const,
        category: "awards",
        type: "teammate-milestone",
        criteria: { requirement: "10 Teammate awards" },
      },
      {
        name: "The Paragon",
        slug: "the-paragon",
        description: "10× Student of the Game",
        icon: "/badges/the-paragon.png",
        color: "#FFD700",
        tier: "hall-of-fame" as const,
        category: "awards",
        type: "student-milestone",
        criteria: { requirement: "10 Student of the Game awards" },
      },
      {
        name: "Dynasty Member",
        slug: "dynasty-member",
        description: "5 years active",
        icon: "/badges/dynasty-member.png",
        color: "#FFD700",
        tier: "hall-of-fame" as const,
        category: "longevity",
        type: "years-active",
        criteria: { requirement: "5 years active" },
      },
      {
        name: "Franchise Player",
        slug: "franchise-player",
        description: "100 total games",
        icon: "/badges/franchise-player.png",
        color: "#FFD700",
        tier: "hall-of-fame" as const,
        category: "games",
        type: "total-games",
        criteria: { requirement: "100 total games" },
      },
      {
        name: "FNH Hall of Famer",
        slug: "fnh-hall-of-famer",
        description: "100 total FNH games",
        icon: "/badges/fnh-hall-of-famer.png",
        color: "#FFD700",
        tier: "hall-of-fame" as const,
        category: "games",
        type: "fnh-games",
        criteria: { requirement: "100 FNH games" },
      },
      {
        name: "Training Titan",
        slug: "training-titan",
        description: "250 practices or 250 skills sessions",
        icon: "/badges/training-titan.png",
        color: "#FFD700",
        tier: "hall-of-fame" as const,
        category: "practices",
        type: "training-sessions",
        criteria: { requirement: "250 practices OR 250 skills sessions" },
      },
      {
        name: "Immortal Ironman",
        slug: "immortal-ironman",
        description: "Attended every one of your team's games in a full year",
        icon: "/badges/immortal-ironman.png",
        color: "#FFD700",
        tier: "hall-of-fame" as const,
        category: "attendance",
        type: "perfect-game-attendance",
        criteria: { requirement: "100% game attendance for 1 full year" },
      },
      {
        name: "Digital Triple Crown",
        slug: "digital-triple-crown",
        description: "Completed 3 full Online Programs",
        icon: "/badges/digital-triple-crown.png",
        color: "#FFD700",
        tier: "hall-of-fame" as const,
        category: "online-training",
        type: "programs-completed",
        criteria: { requirement: "3 full online programs completed" },
      },
      {
        name: "The Completer",
        slug: "the-completer",
        description: "Earned every Superstar badge",
        icon: "/badges/the-completer.png",
        color: "#FFD700",
        tier: "hall-of-fame" as const,
        category: "meta",
        type: "badge-collection",
        criteria: { requirement: "All Superstar badges earned" },
      },
    ];

    // Superstar (Purple) – Elite Consistency
    const superstarBadges = [
      {
        name: "Marquee Player",
        slug: "marquee-player",
        description: "5× MVPs",
        icon: "/badges/marquee-player.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "awards",
        type: "mvp-milestone",
        criteria: { requirement: "5 MVP awards" },
      },
      {
        name: "The Workhorse",
        slug: "the-workhorse",
        description: "5× Hustle",
        icon: "/badges/the-workhorse.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "awards",
        type: "hustle-milestone",
        criteria: { requirement: "5 Hustle awards" },
      },
      {
        name: "The Cornerstone",
        slug: "the-cornerstone",
        description: "5× Teammate",
        icon: "/badges/the-cornerstone.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "awards",
        type: "teammate-milestone",
        criteria: { requirement: "5 Teammate awards" },
      },
      {
        name: "Coach on the Court",
        slug: "coach-on-the-court",
        description: "5× Student of the Game",
        icon: "/badges/coach-on-the-court.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "awards",
        type: "student-milestone",
        criteria: { requirement: "5 Student of the Game awards" },
      },
      {
        name: "Coach's Choice",
        slug: "coaches-choice",
        description: "Earned all 4 major Coach Awards (MVP, Hustle, Teammate, Student) at least once",
        icon: "/badges/coaches-choice.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "awards",
        type: "award-variety",
        criteria: { requirement: "All 4 coach awards earned at least once" },
      },
      {
        name: "Ironman",
        slug: "ironman",
        description: "Played every game in a season",
        icon: "/badges/ironman.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "attendance",
        type: "perfect-game-season",
        criteria: { requirement: "100% game attendance for 1 season" },
      },
      {
        name: "The Pillar",
        slug: "the-pillar",
        description: "Attended every practice in a season",
        icon: "/badges/the-pillar.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "attendance",
        type: "perfect-practice-season",
        criteria: { requirement: "100% practice attendance for 1 season" },
      },
      {
        name: "Practice Centurion",
        slug: "practice-centurion",
        description: "100 practices",
        icon: "/badges/practice-centurion.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "practices",
        type: "practice-count",
        criteria: { requirement: "100 practices" },
      },
      {
        name: "Skills Specialist",
        slug: "skills-specialist",
        description: "100 skills sessions",
        icon: "/badges/skills-specialist.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "practices",
        type: "skills-count",
        criteria: { requirement: "100 skills sessions" },
      },
      {
        name: "Seventy-Five Club",
        slug: "seventy-five-club",
        description: "75 total games",
        icon: "/badges/seventy-five-club.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "games",
        type: "total-games",
        criteria: { requirement: "75 total games" },
      },
      {
        name: "FNH Seventy-Five",
        slug: "fnh-seventy-five",
        description: "75 total FNH games",
        icon: "/badges/fnh-seventy-five.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "games",
        type: "fnh-games",
        criteria: { requirement: "75 FNH games" },
      },
      {
        name: "Team Veteran",
        slug: "team-veteran",
        description: "3 years active",
        icon: "/badges/team-veteran.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "longevity",
        type: "years-active",
        criteria: { requirement: "3 years active" },
      },
      {
        name: "Foundation Graduate",
        slug: "foundation-graduate",
        description: "Completed the Online Foundation Program",
        icon: "/badges/foundation-graduate.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "online-training",
        type: "program-completion",
        criteria: { requirement: "Foundation Program completed" },
      },
      {
        name: "Perfect Attendance (Online)",
        slug: "perfect-attendance-online",
        description: "12 straight weeks of online training program",
        icon: "/badges/perfect-attendance-online.png",
        color: "#9333EA",
        tier: "superstar" as const,
        category: "online-training",
        type: "streak",
        criteria: { requirement: "12 consecutive weeks" },
      },
    ];

    // All-Star (Blue) – Recognition & Milestones
    const allStarBadges = [
      {
        name: "Game Changer",
        slug: "game-changer",
        description: "3× MVPs",
        icon: "/badges/game-changer.png",
        color: "#3B82F6",
        tier: "all-star" as const,
        category: "awards",
        type: "mvp-milestone",
        criteria: { requirement: "3 MVP awards" },
      },
      {
        name: "The Engine",
        slug: "the-engine",
        description: "3× Hustle",
        icon: "/badges/the-engine.png",
        color: "#3B82F6",
        tier: "all-star" as const,
        category: "awards",
        type: "hustle-milestone",
        criteria: { requirement: "3 Hustle awards" },
      },
      {
        name: "The Glue",
        slug: "the-glue",
        description: "3× Teammate",
        icon: "/badges/the-glue.png",
        color: "#3B82F6",
        tier: "all-star" as const,
        category: "awards",
        type: "teammate-milestone",
        criteria: { requirement: "3 Teammate awards" },
      },
      {
        name: "The Protégé",
        slug: "the-protege",
        description: "3× Student of the Game",
        icon: "/badges/the-protege.png",
        color: "#3B82F6",
        tier: "all-star" as const,
        category: "awards",
        type: "student-milestone",
        criteria: { requirement: "3 Student of the Game awards" },
      },
      {
        name: "Practice Fiend",
        slug: "practice-fiend",
        description: "50 practices",
        icon: "/badges/practice-fiend.png",
        color: "#3B82F6",
        tier: "all-star" as const,
        category: "practices",
        type: "practice-count",
        criteria: { requirement: "50 practices" },
      },
      {
        name: "Skills Devotee",
        slug: "skills-devotee",
        description: "50 skills sessions",
        icon: "/badges/skills-devotee.png",
        color: "#3B82F6",
        tier: "all-star" as const,
        category: "practices",
        type: "skills-count",
        criteria: { requirement: "50 skills sessions" },
      },
      {
        name: "Seasoned Competitor",
        slug: "seasoned-competitor",
        description: "50 total games",
        icon: "/badges/seasoned-competitor.png",
        color: "#3B82F6",
        tier: "all-star" as const,
        category: "games",
        type: "total-games",
        criteria: { requirement: "50 total games" },
      },
      {
        name: "FNH Veteran",
        slug: "fnh-veteran",
        description: "50 total FNH games",
        icon: "/badges/fnh-veteran.png",
        color: "#3B82F6",
        tier: "all-star" as const,
        category: "games",
        type: "fnh-games",
        criteria: { requirement: "50 FNH games" },
      },
      {
        name: "First Year Anniversary",
        slug: "first-year-anniversary",
        description: "1 year active",
        icon: "/badges/first-year-anniversary.png",
        color: "#3B82F6",
        tier: "all-star" as const,
        category: "longevity",
        type: "years-active",
        criteria: { requirement: "1 year active" },
      },
      {
        name: "Digital Scholar",
        slug: "digital-scholar",
        description: "Completed 6 consecutive weeks of any online training program",
        icon: "/badges/digital-scholar.png",
        color: "#3B82F6",
        tier: "all-star" as const,
        category: "online-training",
        type: "streak",
        criteria: { requirement: "6 consecutive weeks" },
      },
    ];

    // Starter (Green) – Habit Builders
    const starterBadges = [
      {
        name: "Locked In",
        slug: "locked-in",
        description: "10 consecutive practices",
        icon: "/badges/locked-in.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "practices",
        type: "streak",
        criteria: { requirement: "10 consecutive practices" },
      },
      {
        name: "Dedicated Grinder",
        slug: "dedicated-grinder",
        description: "25 practices",
        icon: "/badges/dedicated-grinder.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "practices",
        type: "practice-count",
        criteria: { requirement: "25 practices" },
      },
      {
        name: "Skills Seeker",
        slug: "skills-seeker",
        description: "25 skills sessions",
        icon: "/badges/skills-seeker.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "practices",
        type: "skills-count",
        criteria: { requirement: "25 skills sessions" },
      },
      {
        name: "Regular Competitor",
        slug: "regular-competitor",
        description: "25 total games",
        icon: "/badges/regular-competitor.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "games",
        type: "total-games",
        criteria: { requirement: "25 total games" },
      },
      {
        name: "FNH Regular",
        slug: "fnh-regular",
        description: "25 total FNH games",
        icon: "/badges/fnh-regular.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "games",
        type: "fnh-games",
        criteria: { requirement: "25 FNH games" },
      },
      {
        name: "RSVP Streak",
        slug: "rsvp-streak",
        description: "Submitted RSVPs on time for 5 straight events",
        icon: "/badges/rsvp-streak.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "engagement",
        type: "rsvp-streak",
        criteria: { requirement: "5 consecutive on-time RSVPs" },
      },
      {
        name: "Practice Partner",
        slug: "practice-partner",
        description: "Attended every scheduled practice in a single week",
        icon: "/badges/practice-partner.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "attendance",
        type: "weekly-perfect",
        criteria: { requirement: "100% practice attendance in 1 week" },
      },
      {
        name: "Film Student",
        slug: "film-student",
        description: "Completed 5 online videos (any type)",
        icon: "/badges/film-student.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "online-training",
        type: "video-count",
        criteria: { requirement: "5 online videos" },
      },
      {
        name: "Back-to-Back Sessions",
        slug: "back-to-back-sessions",
        description: "Completed weekly online videos 2 weeks in a row",
        icon: "/badges/back-to-back-sessions.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "online-training",
        type: "streak",
        criteria: { requirement: "2 consecutive weeks" },
      },
      // Coach Awards (Awarded by Coach at any time)
      {
        name: "Game MVP",
        slug: "game-mvp",
        description: "Awarded by coach for exceptional game performance",
        icon: "/badges/game-mvp.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "awards",
        type: "coach-award",
        criteria: { requirement: "Coach awarded" },
      },
      {
        name: "Hustle Award",
        slug: "hustle-award",
        description: "Awarded by coach for exceptional effort and determination",
        icon: "/badges/hustle-award.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "awards",
        type: "coach-award",
        criteria: { requirement: "Coach awarded" },
      },
      {
        name: "Teammate Award",
        slug: "teammate-award",
        description: "Awarded by coach for exceptional teamwork and support",
        icon: "/badges/teammate-award.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "awards",
        type: "coach-award",
        criteria: { requirement: "Coach awarded" },
      },
      {
        name: "Student of the Game",
        slug: "student-of-the-game",
        description: "Awarded by coach for exceptional basketball IQ and learning",
        icon: "/badges/student-of-the-game.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "awards",
        type: "coach-award",
        criteria: { requirement: "Coach awarded" },
      },
      {
        name: "Recruiter",
        slug: "recruiter",
        description: "For bringing in a new player who joins",
        icon: "/badges/recruiter.png",
        color: "#22C55E",
        tier: "starter" as const,
        category: "engagement",
        type: "recruitment",
        criteria: { requirement: "Recruited 1 new player" },
      },
    ];

    // Prospect (Grey) – First Steps
    const prospectBadges = [
      {
        name: "The Debut",
        slug: "the-debut",
        description: "First game played",
        icon: "/badges/the-debut.png",
        color: "#6B7280",
        tier: "prospect" as const,
        category: "games",
        type: "first-game",
        criteria: { requirement: "1 game played" },
      },
      {
        name: "Friday Lights",
        slug: "friday-lights",
        description: "First FNH game",
        icon: "/badges/friday-lights.png",
        color: "#6B7280",
        tier: "prospect" as const,
        category: "games",
        type: "first-fnh",
        criteria: { requirement: "1 FNH game played" },
      },
      {
        name: "Practice Rookie",
        slug: "practice-rookie",
        description: "10 practices",
        icon: "/badges/practice-rookie.png",
        color: "#6B7280",
        tier: "prospect" as const,
        category: "practices",
        type: "practice-count",
        criteria: { requirement: "10 practices" },
      },
      {
        name: "Skill Starter",
        slug: "skill-starter",
        description: "10 skills sessions",
        icon: "/badges/skill-starter.png",
        color: "#6B7280",
        tier: "prospect" as const,
        category: "practices",
        type: "skills-count",
        criteria: { requirement: "10 skills sessions" },
      },
      {
        name: "Game Planner",
        slug: "game-planner",
        description: "First RSVP to UYP event",
        icon: "/badges/game-planner.png",
        color: "#6B7280",
        tier: "prospect" as const,
        category: "engagement",
        type: "first-rsvp",
        criteria: { requirement: "1 RSVP submitted" },
      },
      {
        name: "Checked In",
        slug: "checked-in",
        description: "Checked-in to first UYP event",
        icon: "/badges/checked-in.png",
        color: "#6B7280",
        tier: "prospect" as const,
        category: "engagement",
        type: "first-checkin",
        criteria: { requirement: "1 check-in completed" },
      },
      {
        name: "Road Warrior",
        slug: "road-warrior",
        description: "Attended event at a different location",
        icon: "/badges/road-warrior.png",
        color: "#6B7280",
        tier: "prospect" as const,
        category: "engagement",
        type: "away-event",
        criteria: { requirement: "1 event at different location" },
      },
      {
        name: "Film Rookie",
        slug: "film-rookie",
        description: "First online training video",
        icon: "/badges/film-rookie.png",
        color: "#6B7280",
        tier: "prospect" as const,
        category: "online-training",
        type: "first-video",
        criteria: { requirement: "1 online video completed" },
      },
      {
        name: "First Ten",
        slug: "first-ten",
        description: "10 total games",
        icon: "/badges/first-ten.png",
        color: "#6B7280",
        tier: "prospect" as const,
        category: "games",
        type: "total-games",
        criteria: { requirement: "10 total games" },
      },
      {
        name: "FNH Rookie",
        slug: "fnh-rookie",
        description: "10 total FNH games",
        icon: "/badges/fnh-rookie.png",
        color: "#6B7280",
        tier: "prospect" as const,
        category: "games",
        type: "fnh-games",
        criteria: { requirement: "10 FNH games" },
      },
    ];

    // Combine all badges
    const allBadges = [
      ...hallOfFameBadges,
      ...superstarBadges,
      ...allStarBadges,
      ...starterBadges,
      ...prospectBadges,
    ];

    // Upsert badges (insert or update based on slug)
    for (const badge of allBadges) {
      await db.insert(badges)
        .values(badge)
        .onConflictDoUpdate({
          target: badges.slug,
          set: badge,
        });
    }
    console.log(`  ✓ Seeded ${allBadges.length} badges (${hallOfFameBadges.length} Hall of Fame, ${superstarBadges.length} Superstar, ${allStarBadges.length} All-Star, ${starterBadges.length} Starter, ${prospectBadges.length} Prospect)`);

    console.log("✅ Badge and trophy seeding completed successfully!");
    console.log(`   Total: ${trophyData.length} trophies, ${allBadges.length} badges`);
    
    return {
      trophies: trophyData.length,
      badges: allBadges.length,
    };
  } catch (error) {
    console.error("❌ Error seeding badges and trophies:", error);
    throw error;
  }
};

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedBadgesAndTrophies()
    .then(() => {
      console.log("Done!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("Failed:", error);
      process.exit(1);
    });
}
