import { Award } from "@shared/awards.types";

export const AWARDS: Award[] = [
  // ==================== HALL OF FAMER BADGES (Yellow) ====================
  {
    id: "superstar-10x-mvp",
    kind: "Badge",
    name: "Superstar (10× MVP)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For demonstrating a consistent pattern of dominance.",
    iconName: "badge-superstar-supreme",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 10 },
    triggerSources: ["coachAward"],
    tags: ["MVP", "Elite"]
  },
  {
    id: "prime-time-10x-clutch",
    kind: "Badge",
    name: "Prime Time (10× Clutch)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For being known to deliver in the biggest moments.",
    iconName: "badge-prime-time",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 10 },
    triggerSources: ["coachAward"],
    tags: ["Clutch", "Elite"]
  },
  {
    id: "force-of-will-10x-comeback",
    kind: "Badge",
    name: "Force of Will (10× Comeback)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For an unbreakable spirit that refuses to lose.",
    iconName: "badge-force-of-will",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 10 },
    triggerSources: ["coachAward"],
    tags: ["Comeback", "Elite"]
  },
  {
    id: "relentless-10x-hustle",
    kind: "Badge",
    name: "Relentless (10× Hustle)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For a motor that never stops.",
    iconName: "badge-relentless",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 10 },
    triggerSources: ["coachAward"],
    tags: ["Hustle", "Elite"]
  },
  {
    id: "the-linchpin-10x-teammate",
    kind: "Badge",
    name: "The Linchpin (10× Teammate)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For being absolutely essential to team cohesion.",
    iconName: "badge-the-linchpin",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 10 },
    triggerSources: ["coachAward"],
    tags: ["Teammate", "Elite"]
  },
  {
    id: "spirit-of-game-10x-sportsmanship",
    kind: "Badge",
    name: "Spirit of the Game (10× Sportsmanship)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For embodying the highest ideals of fair play.",
    iconName: "badge-spirit-of-game",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 10 },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship", "Elite"]
  },
  {
    id: "coach-on-court-10x-student",
    kind: "Badge",
    name: "Coach on the Court (10× Student)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For understanding the game on a deeper, strategic level.",
    iconName: "badge-coach-on-the-court",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 10 },
    triggerSources: ["coachAward"],
    tags: ["Student", "Elite"]
  },
  {
    id: "the-paragon-10x-lead-by-example",
    kind: "Badge",
    name: "The Paragon (10× Lead by Example)",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For being the ultimate embodiment of how to prepare and play.",
    iconName: "badge-the-paragon",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 10 },
    triggerSources: ["coachAward"],
    tags: ["Leadership", "Elite"]
  },
  {
    id: "coaches-choice-collection",
    kind: "Badge",
    name: "Coach's Choice",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For earning each of the eight core coach awards at least once.",
    iconName: "badge-coaches-choice",
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["Collection", "Elite"]
  },
  {
    id: "the-trifecta",
    kind: "Badge",
    name: "The Trifecta",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For earning an MVP, Hustle, and Teammate award in the same season.",
    iconName: "badge-trifecta",
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["Seasonal", "Elite"]
  },
  {
    id: "character-captain",
    kind: "Badge",
    name: "Character Captain",
    tier: "HallOfFamer",
    category: "InGamePerformance",
    description: "For earning a Hustle, Teammate, and Sportsmanship award in the same season.",
    iconName: "badge-character-captain",
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["Character", "Elite"]
  },
  {
    id: "practice-legend",
    kind: "Badge",
    name: "Practice Legend",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "For attending 250 total team practices.",
    iconName: "badge-practice-legend",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 250 },
    triggerSources: ["attendance"],
    tags: ["Practice", "Elite"]
  },
  {
    id: "skills-virtuoso",
    kind: "Badge",
    name: "Skills Virtuoso",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "For attending 250 total skills sessions.",
    iconName: "badge-skills-virtuoso",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 250 },
    triggerSources: ["attendance"],
    tags: ["Skills", "Elite"]
  },
  {
    id: "franchise-player",
    kind: "Badge",
    name: "Franchise Player",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "For playing in 250 total games.",
    iconName: "badge-franchise-player",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 250 },
    triggerSources: ["attendance"],
    tags: ["Games", "Elite"]
  },
  {
    id: "fnh-hall-of-famer",
    kind: "Badge",
    name: "FNH Hall of Famer",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "For playing in 250 total FNH games.",
    iconName: "badge-fnh-hall-of-famer",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 250 },
    triggerSources: ["attendance"],
    tags: ["FNH", "Elite"]
  },
  {
    id: "dynasty-member",
    kind: "Badge",
    name: "Dynasty Member",
    tier: "HallOfFamer",
    category: "Attendance",
    description: "For being an active member of the team for five full years.",
    iconName: "badge-dynasty-member",
    progressKind: "counter",
    counterOf: { stat: "yearsActive", target: 5 },
    triggerSources: ["attendance"],
    tags: ["Loyalty", "Elite"]
  },
  {
    id: "foundation-alumnus",
    kind: "Badge",
    name: "Foundation Alumnus",
    tier: "HallOfFamer",
    category: "TrainingProgram",
    description: "For completing the entire 12-week Foundation Program a second time.",
    iconName: "badge-foundation-alumnus",
    progressKind: "manual",
    triggerSources: ["trainingCompletion"],
    tags: ["Online", "Elite"]
  },

  // ==================== SUPERSTAR BADGES (Purple) ====================
  {
    id: "marquee-player-5x-mvp",
    kind: "Badge",
    name: "Marquee Player (5× MVP)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For being a recognized star and reliable top performer.",
    iconName: "badge-marquee-player",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 5 },
    triggerSources: ["coachAward"],
    tags: ["MVP", "Advanced"]
  },
  {
    id: "ice-in-veins-5x-clutch",
    kind: "Badge",
    name: "Ice in the Veins (5× Clutch)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For thriving under pressure.",
    iconName: "badge-ice-in-veins",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 5 },
    triggerSources: ["coachAward"],
    tags: ["Clutch", "Advanced"]
  },
  {
    id: "momentum-shifter-5x-comeback",
    kind: "Badge",
    name: "Momentum Shifter (5× Comeback)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For changing the tone of a game.",
    iconName: "badge-momentum-shifter",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 5 },
    triggerSources: ["coachAward"],
    tags: ["Comeback", "Advanced"]
  },
  {
    id: "the-workhorse-5x-hustle",
    kind: "Badge",
    name: "The Workhorse (5× Hustle)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For having an elite work ethic.",
    iconName: "badge-the-workhorse",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 5 },
    triggerSources: ["coachAward"],
    tags: ["Hustle", "Advanced"]
  },
  {
    id: "the-cornerstone-5x-teammate",
    kind: "Badge",
    name: "The Cornerstone (5× Teammate)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For being a player the team is built around emotionally.",
    iconName: "badge-the-cornerstone",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 5 },
    triggerSources: ["coachAward"],
    tags: ["Teammate", "Advanced"]
  },
  {
    id: "the-ambassador-5x-sportsmanship",
    kind: "Badge",
    name: "The Ambassador (5× Sportsmanship)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For being a positive representative of the team.",
    iconName: "badge-ambassador",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 5 },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship", "Advanced"]
  },
  {
    id: "the-tactician-5x-student",
    kind: "Badge",
    name: "The Tactician (5× Student)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For a high in-game IQ.",
    iconName: "badge-tactician",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 5 },
    triggerSources: ["coachAward"],
    tags: ["Student", "Advanced"]
  },
  {
    id: "the-blueprint-5x-lead-by-example",
    kind: "Badge",
    name: "The Blueprint (5× Lead by Example)",
    tier: "Superstar",
    category: "InGamePerformance",
    description: "For providing a model for others to follow.",
    iconName: "badge-blueprint",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 5 },
    triggerSources: ["coachAward"],
    tags: ["Leadership", "Advanced"]
  },
  {
    id: "the-pillar",
    kind: "Badge",
    name: "The Pillar",
    tier: "Superstar",
    category: "Attendance",
    description: "For attending every single scheduled practice in a season.",
    iconName: "badge-the-pillar",
    progressKind: "manual",
    triggerSources: ["attendance"],
    tags: ["Practice", "Perfect"]
  },
  {
    id: "ironman",
    kind: "Badge",
    name: "Ironman",
    tier: "Superstar",
    category: "Attendance",
    description: "For playing in every single game of a season.",
    iconName: "badge-ironman",
    progressKind: "manual",
    triggerSources: ["attendance"],
    tags: ["Games", "Perfect"]
  },
  {
    id: "fnh-ironman",
    kind: "Badge",
    name: "FNH Ironman",
    tier: "Superstar",
    category: "Attendance",
    description: "For playing in every FNH game in a single season.",
    iconName: "badge-immortal-ironman",
    progressKind: "manual",
    triggerSources: ["attendance"],
    tags: ["FNH", "Perfect"]
  },
  {
    id: "practice-centurion",
    kind: "Badge",
    name: "Practice Centurion",
    tier: "Superstar",
    category: "Attendance",
    description: "For attending 100 total team practices.",
    iconName: "badge-practice-centurion",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 100 },
    triggerSources: ["attendance"],
    tags: ["Practice", "Advanced"]
  },
  {
    id: "skills-specialist",
    kind: "Badge",
    name: "Skills Specialist",
    tier: "Superstar",
    category: "Attendance",
    description: "For attending 100 total skills sessions.",
    iconName: "badge-skills-specialist",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 100 },
    triggerSources: ["attendance"],
    tags: ["Skills", "Advanced"]
  },
  {
    id: "century-club",
    kind: "Badge",
    name: "Century Club",
    tier: "Superstar",
    category: "Attendance",
    description: "For playing in 100 total games.",
    iconName: "badge-century-club",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 100 },
    triggerSources: ["attendance"],
    tags: ["Games", "Advanced"]
  },
  {
    id: "fnh-legend",
    kind: "Badge",
    name: "FNH Legend",
    tier: "Superstar",
    category: "Attendance",
    description: "For playing in 100 total FNH games.",
    iconName: "badge-fnh-legend",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 100 },
    triggerSources: ["attendance"],
    tags: ["FNH", "Advanced"]
  },
  {
    id: "team-veteran",
    kind: "Badge",
    name: "Team Veteran",
    tier: "Superstar",
    category: "Attendance",
    description: "For being an active member of the team for three full years.",
    iconName: "badge-team-veteran",
    progressKind: "counter",
    counterOf: { stat: "yearsActive", target: 3 },
    triggerSources: ["attendance"],
    tags: ["Loyalty", "Advanced"]
  },
  {
    id: "foundation-graduate",
    kind: "Badge",
    name: "Foundation Graduate",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "For completing all 60 videos in the 12-week Foundation Program.",
    iconName: "badge-foundation-graduate",
    progressKind: "counter",
    counterOf: { stat: "totalVideos", target: 60 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Advanced"]
  },
  {
    id: "technique-titan",
    kind: "Badge",
    name: "Technique Titan",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "For completing all 36 Skill videos in the program.",
    iconName: "badge-technique-titan",
    progressKind: "counter",
    counterOf: { stat: "skillsCompleted", target: 36 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Skills"]
  },
  {
    id: "peak-performer",
    kind: "Badge",
    name: "Peak Performer",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "For completing all 12 Strength & Conditioning videos in the program.",
    iconName: "badge-peak-performer",
    progressKind: "counter",
    counterOf: { stat: "scCompleted", target: 12 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Conditioning"]
  },
  {
    id: "basketball-savant",
    kind: "Badge",
    name: "Basketball Savant",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "For completing all 12 Basketball IQ videos in the program.",
    iconName: "badge-basketball-savant",
    progressKind: "counter",
    counterOf: { stat: "iqCompleted", target: 12 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "IQ"]
  },
  {
    id: "perfect-attendance-online",
    kind: "Badge",
    name: "Perfect Attendance: Online",
    tier: "Superstar",
    category: "TrainingProgram",
    description: "For completing all required videos each week for 12 consecutive weeks.",
    iconName: "badge-perfect-attendance-online",
    progressKind: "manual",
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Perfect"]
  },

  // ==================== ALL-STAR BADGES (Blue) ====================
  {
    id: "game-changer-3x-mvp",
    kind: "Badge",
    name: "Game Changer (3× MVP)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For consistently making a pivotal impact.",
    iconName: "badge-game-changer",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 3 },
    triggerSources: ["coachAward"],
    tags: ["MVP", "Intermediate"]
  },
  {
    id: "the-closer-3x-clutch",
    kind: "Badge",
    name: "The Closer (3× Clutch)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For making multiple high-pressure plays.",
    iconName: "badge-closer",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 3 },
    triggerSources: ["coachAward"],
    tags: ["Clutch", "Intermediate"]
  },
  {
    id: "the-sparkplug-3x-comeback",
    kind: "Badge",
    name: "The Sparkplug (3× Comeback)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For consistently igniting team rallies.",
    iconName: "badge-sparkplug",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 3 },
    triggerSources: ["coachAward"],
    tags: ["Comeback", "Intermediate"]
  },
  {
    id: "the-engine-3x-hustle",
    kind: "Badge",
    name: "The Engine (3× Hustle)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For being a consistent source of energy.",
    iconName: "badge-the-engine",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 3 },
    triggerSources: ["coachAward"],
    tags: ["Hustle", "Intermediate"]
  },
  {
    id: "the-glue-3x-teammate",
    kind: "Badge",
    name: "The Glue (3× Teammate)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For being a positive and unifying presence.",
    iconName: "badge-the-glue",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 3 },
    triggerSources: ["coachAward"],
    tags: ["Teammate", "Intermediate"]
  },
  {
    id: "class-act-3x-sportsmanship",
    kind: "Badge",
    name: "Class Act (3× Sportsmanship)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For consistent respectful conduct.",
    iconName: "badge-class-act",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 3 },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship", "Intermediate"]
  },
  {
    id: "the-protege-3x-student",
    kind: "Badge",
    name: "The Protégé (3× Student)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For being exceptionally coachable and attentive.",
    iconName: "badge-the-protege",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 3 },
    triggerSources: ["coachAward"],
    tags: ["Student", "Intermediate"]
  },
  {
    id: "the-standard-3x-lead-by-example",
    kind: "Badge",
    name: "The Standard (3× Lead by Example)",
    tier: "AllStar",
    category: "InGamePerformance",
    description: "For setting the bar for effort and execution.",
    iconName: "badge-standard",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 3 },
    triggerSources: ["coachAward"],
    tags: ["Leadership", "Intermediate"]
  },
  {
    id: "the-dependable",
    kind: "Badge",
    name: "The Dependable",
    tier: "AllStar",
    category: "Attendance",
    description: "For submitting a timely RSVP for every event in a season.",
    iconName: "badge-dependable",
    progressKind: "manual",
    triggerSources: ["rsvp"],
    tags: ["RSVP", "Perfect"]
  },
  {
    id: "recruiter",
    kind: "Badge",
    name: "Recruiter",
    tier: "AllStar",
    category: "Attendance",
    description: "For referring a new player who joins.",
    iconName: "badge-recruiter",
    progressKind: "counter",
    counterOf: { stat: "referrals", target: 1 },
    triggerSources: ["attendance"],
    tags: ["Referral", "Community"]
  },
  {
    id: "practice-fiend",
    kind: "Badge",
    name: "Practice Fiend",
    tier: "AllStar",
    category: "Attendance",
    description: "For attending 50 total practices.",
    iconName: "badge-practice-fiend",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 50 },
    triggerSources: ["attendance"],
    tags: ["Practice", "Intermediate"]
  },
  {
    id: "skills-devotee",
    kind: "Badge",
    name: "Skills Devotee",
    tier: "AllStar",
    category: "Attendance",
    description: "For attending 50 total skills sessions.",
    iconName: "badge-skills-devotee",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 50 },
    triggerSources: ["attendance"],
    tags: ["Skills", "Intermediate"]
  },
  {
    id: "seasoned-competitor",
    kind: "Badge",
    name: "Seasoned Competitor",
    tier: "AllStar",
    category: "Attendance",
    description: "For playing in 50 total games.",
    iconName: "badge-seasoned-competitor",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 50 },
    triggerSources: ["attendance"],
    tags: ["Games", "Intermediate"]
  },
  {
    id: "fnh-veteran",
    kind: "Badge",
    name: "FNH Veteran",
    tier: "AllStar",
    category: "Attendance",
    description: "For playing in 50 total FNH games.",
    iconName: "badge-fnh-veteran",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 50 },
    triggerSources: ["attendance"],
    tags: ["FNH", "Intermediate"]
  },
  {
    id: "first-year-anniversary",
    kind: "Badge",
    name: "First Year Anniversary",
    tier: "AllStar",
    category: "Attendance",
    description: "For being an active member of the team for one full year.",
    iconName: "badge-first-year-anniversary",
    progressKind: "counter",
    counterOf: { stat: "yearsActive", target: 1 },
    triggerSources: ["attendance"],
    tags: ["Loyalty", "Milestone"]
  },
  {
    id: "half-time-adjustments",
    kind: "Badge",
    name: "Half-Time Adjustments",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "For completing 30 total videos in the Foundation Program.",
    iconName: "badge-half-time-adjustments",
    progressKind: "counter",
    counterOf: { stat: "totalVideos", target: 30 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Milestone"]
  },
  {
    id: "monthly-module-master",
    kind: "Badge",
    name: "Monthly Module Master",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "For completing all assigned videos for four consecutive weeks.",
    iconName: "badge-monthly-module-master",
    progressKind: "manual",
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Consistency"]
  },
  {
    id: "skills-sharp-shooter",
    kind: "Badge",
    name: "Skills Sharp-Shooter",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "For completing 20 different Skill videos.",
    iconName: "badge-skills-sharp-shooter",
    progressKind: "counter",
    counterOf: { stat: "skillsCompleted", target: 20 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Skills"]
  },
  {
    id: "conditioning-core",
    kind: "Badge",
    name: "Conditioning Core",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "For completing 6 different Strength & Conditioning videos.",
    iconName: "badge-conditioning-core",
    progressKind: "counter",
    counterOf: { stat: "scCompleted", target: 6 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Conditioning"]
  },
  {
    id: "strategic-specialist",
    kind: "Badge",
    name: "Strategic Specialist",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "For completing 6 different Basketball IQ videos.",
    iconName: "badge-strategic-specialist",
    progressKind: "counter",
    counterOf: { stat: "iqCompleted", target: 6 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "IQ"]
  },
  {
    id: "mid-season-mentor",
    kind: "Badge",
    name: "Mid-Season Mentor",
    tier: "AllStar",
    category: "TrainingProgram",
    description: "For completing all weekly videos for 6 consecutive weeks.",
    iconName: "badge-mid-season-mentor",
    progressKind: "manual",
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Consistency"]
  },

  // ==================== STARTER BADGES (Green) ====================
  {
    id: "locked-in",
    kind: "Badge",
    name: "Locked In",
    tier: "Starter",
    category: "Attendance",
    description: "For attending 10 consecutive scheduled practices.",
    iconName: "badge-locked-in",
    progressKind: "streak",
    streakOf: { stat: "practiceStreak", target: 10 },
    triggerSources: ["attendance"],
    tags: ["Practice", "Consistency"]
  },
  {
    id: "on-the-ball",
    kind: "Badge",
    name: "On the Ball",
    tier: "Starter",
    category: "Attendance",
    description: "For submitting a timely RSVP for 10 consecutive events.",
    iconName: "badge-on-the-ball",
    progressKind: "streak",
    streakOf: { stat: "rsvpStreak", target: 10 },
    triggerSources: ["rsvp"],
    tags: ["RSVP", "Consistency"]
  },
  {
    id: "tournament-titan",
    kind: "Badge",
    name: "Tournament Titan",
    tier: "Starter",
    category: "Attendance",
    description: "For checking into all games in a single tournament.",
    iconName: "badge-tournament-titan",
    progressKind: "manual",
    triggerSources: ["attendance"],
    tags: ["Tournament", "Perfect"]
  },
  {
    id: "dedicated-grinder",
    kind: "Badge",
    name: "Dedicated Grinder",
    tier: "Starter",
    category: "Attendance",
    description: "For attending 25 total practices.",
    iconName: "badge-dedicated-grinder",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 25 },
    triggerSources: ["attendance"],
    tags: ["Practice", "Basic"]
  },
  {
    id: "skills-seeker",
    kind: "Badge",
    name: "Skills Seeker",
    tier: "Starter",
    category: "Attendance",
    description: "For attending 25 total skills sessions.",
    iconName: "badge-skills-seeker",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 25 },
    triggerSources: ["attendance"],
    tags: ["Skills", "Basic"]
  },
  {
    id: "regular-competitor",
    kind: "Badge",
    name: "Regular Competitor",
    tier: "Starter",
    category: "Attendance",
    description: "For playing in 25 total games.",
    iconName: "badge-regular-competitor",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 25 },
    triggerSources: ["attendance"],
    tags: ["Games", "Basic"]
  },
  {
    id: "fnh-regular",
    kind: "Badge",
    name: "FNH Regular",
    tier: "Starter",
    category: "Attendance",
    description: "For playing in 25 total FNH games.",
    iconName: "badge-fnh-regular",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 25 },
    triggerSources: ["attendance"],
    tags: ["FNH", "Basic"]
  },
  {
    id: "game-mvp",
    kind: "Badge",
    name: "Game MVP",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Instrumental in the team's performance during a single game.",
    iconName: "badge-game-mvp",
    progressKind: "counter",
    counterOf: { stat: "mvpCount", target: 1 },
    triggerSources: ["coachAward"],
    tags: ["MVP", "Single"]
  },
  {
    id: "clutch-player",
    kind: "Badge",
    name: "Clutch Player",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Given for making a game-changing play under pressure.",
    iconName: "badge-clutch-player",
    progressKind: "counter",
    counterOf: { stat: "clutchCount", target: 1 },
    triggerSources: ["coachAward"],
    tags: ["Clutch", "Single"]
  },
  {
    id: "comeback-kid",
    kind: "Badge",
    name: "Comeback Kid",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Given for energy that was instrumental in a team rally.",
    iconName: "badge-comeback-kid",
    progressKind: "counter",
    counterOf: { stat: "comebackCount", target: 1 },
    triggerSources: ["coachAward"],
    tags: ["Comeback", "Single"]
  },
  {
    id: "sportsmanship-award",
    kind: "Badge",
    name: "Sportsmanship Award",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Display of outstanding sportsmanship.",
    iconName: "badge-spirit-award",
    progressKind: "counter",
    counterOf: { stat: "sportsmanshipCount", target: 1 },
    triggerSources: ["coachAward"],
    tags: ["Sportsmanship", "Single"]
  },
  {
    id: "hustle-award",
    kind: "Badge",
    name: "Hustle Award",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Relentless hustle and effort.",
    iconName: "badge-hustle-award",
    progressKind: "counter",
    counterOf: { stat: "hustleCount", target: 1 },
    triggerSources: ["coachAward"],
    tags: ["Hustle", "Single"]
  },
  {
    id: "teammate-award",
    kind: "Badge",
    name: "Teammate Award",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Encouraging, supportive, or unselfish play.",
    iconName: "badge-teammate-award",
    progressKind: "counter",
    counterOf: { stat: "teammateCount", target: 1 },
    triggerSources: ["coachAward"],
    tags: ["Teammate", "Single"]
  },
  {
    id: "student-of-the-game",
    kind: "Badge",
    name: "Student of the Game",
    tier: "Starter",
    category: "InGamePerformance",
    description: "Exceptional listening skills and attentiveness.",
    iconName: "badge-student-of-the-game",
    progressKind: "counter",
    counterOf: { stat: "studentCount", target: 1 },
    triggerSources: ["coachAward"],
    tags: ["Student", "Single"]
  },
  {
    id: "lead-by-example",
    kind: "Badge",
    name: "Lead by Example",
    tier: "Starter",
    category: "InGamePerformance",
    description: "For flawlessly demonstrating a drill or skill.",
    iconName: "badge-lead-by-example",
    progressKind: "counter",
    counterOf: { stat: "leadByExampleCount", target: 1 },
    triggerSources: ["coachAward"],
    tags: ["Leadership", "Single"]
  },
  {
    id: "weekly-warm-up",
    kind: "Badge",
    name: "Weekly Warm-Up",
    tier: "Starter",
    category: "TrainingProgram",
    description: "For completing all 5 assigned videos in a single week.",
    iconName: "badge-weekly-warm-up",
    progressKind: "manual",
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Weekly"]
  },
  {
    id: "film-study",
    kind: "Badge",
    name: "Film Study",
    tier: "Starter",
    category: "TrainingProgram",
    description: "For completing 10 total online training videos.",
    iconName: "badge-film-study",
    progressKind: "counter",
    counterOf: { stat: "totalVideos", target: 10 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Basic"]
  },
  {
    id: "skill-builder",
    kind: "Badge",
    name: "Skill Builder",
    tier: "Starter",
    category: "TrainingProgram",
    description: "For completing 5 different Skill videos.",
    iconName: "badge-skill-builder",
    progressKind: "counter",
    counterOf: { stat: "skillsCompleted", target: 5 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Skills"]
  },
  {
    id: "foundation-force",
    kind: "Badge",
    name: "Foundation Force",
    tier: "Starter",
    category: "TrainingProgram",
    description: "For completing 5 different Strength & Conditioning videos.",
    iconName: "badge-foundation-force",
    progressKind: "counter",
    counterOf: { stat: "scCompleted", target: 5 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Conditioning"]
  },
  {
    id: "court-visionary",
    kind: "Badge",
    name: "Court Visionary",
    tier: "Starter",
    category: "TrainingProgram",
    description: "For completing 5 different Basketball IQ videos.",
    iconName: "badge-court-visionary",
    progressKind: "counter",
    counterOf: { stat: "iqCompleted", target: 5 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "IQ"]
  },
  {
    id: "back-to-back-sessions",
    kind: "Badge",
    name: "Back-to-Back Sessions",
    tier: "Starter",
    category: "TrainingProgram",
    description: "For completing all weekly videos two weeks in a row.",
    iconName: "badge-back-to-back-sessions",
    progressKind: "manual",
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Consistency"]
  },

  // ==================== PROSPECT BADGES (Grey) ====================
  {
    id: "checked-in",
    kind: "Badge",
    name: "Checked In",
    tier: "Prospect",
    category: "Attendance",
    description: "For checking into any UYP event.",
    iconName: "badge-checked-in",
    progressKind: "manual",
    triggerSources: ["attendance"],
    tags: ["CheckIn", "First"]
  },
  {
    id: "road-warrior",
    kind: "Badge",
    name: "Road Warrior",
    tier: "Prospect",
    category: "Attendance",
    description: "For checking into an event at a different location.",
    iconName: "badge-road-warrior",
    progressKind: "manual",
    triggerSources: ["attendance"],
    tags: ["Location", "First"]
  },
  {
    id: "holiday-hero",
    kind: "Badge",
    name: "Holiday Hero",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in a game on a major holiday.",
    iconName: "badge-holiday-hero",
    progressKind: "counter",
    counterOf: { stat: "holidayGamesCount", target: 1 },
    triggerSources: ["attendance"],
    tags: ["Holiday", "First"]
  },
  {
    id: "the-debut",
    kind: "Badge",
    name: "The Debut",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in your very first game.",
    iconName: "badge-the-debut",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 1 },
    triggerSources: ["attendance"],
    tags: ["Game", "First"]
  },
  {
    id: "friday-follower",
    kind: "Badge",
    name: "Friday Follower",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in your first Friday Night Hoops game.",
    iconName: "badge-friday-follower",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 1 },
    triggerSources: ["attendance"],
    tags: ["FNH", "First"]
  },
  {
    id: "heating-up",
    kind: "Badge",
    name: "Heating Up",
    tier: "Prospect",
    category: "Attendance",
    description: "For attending 5 consecutive scheduled practices.",
    iconName: "badge-heating-up",
    progressKind: "streak",
    streakOf: { stat: "practiceStreak", target: 5 },
    triggerSources: ["attendance"],
    tags: ["Practice", "Streak"]
  },
  {
    id: "game-planner",
    kind: "Badge",
    name: "Game Planner",
    tier: "Prospect",
    category: "Attendance",
    description: "For RSVPing to a Game within its proper window.",
    iconName: "badge-game-planner",
    progressKind: "manual",
    triggerSources: ["rsvp"],
    tags: ["RSVP", "First"]
  },
  {
    id: "practice-planner",
    kind: "Badge",
    name: "Practice Planner",
    tier: "Prospect",
    category: "Attendance",
    description: "For RSVPing to a Practice, Skill, or FNH event.",
    iconName: "badge-practice-planner",
    progressKind: "manual",
    triggerSources: ["rsvp"],
    tags: ["RSVP", "First"]
  },
  {
    id: "first-reps",
    kind: "Badge",
    name: "First Reps",
    tier: "Prospect",
    category: "Attendance",
    description: "For attending 10 total practices.",
    iconName: "badge-first-reps",
    progressKind: "counter",
    counterOf: { stat: "practicesTotal", target: 10 },
    triggerSources: ["attendance"],
    tags: ["Practice", "Milestone"]
  },
  {
    id: "skill-starter",
    kind: "Badge",
    name: "Skill Starter",
    tier: "Prospect",
    category: "Attendance",
    description: "For attending 10 total skills sessions.",
    iconName: "badge-skill-starter",
    progressKind: "counter",
    counterOf: { stat: "skillsTotal", target: 10 },
    triggerSources: ["attendance"],
    tags: ["Skills", "Milestone"]
  },
  {
    id: "first-ten",
    kind: "Badge",
    name: "First Ten",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in 10 total games.",
    iconName: "badge-first-ten",
    progressKind: "counter",
    counterOf: { stat: "gamesTotal", target: 10 },
    triggerSources: ["attendance"],
    tags: ["Games", "Milestone"]
  },
  {
    id: "fnh-fighter",
    kind: "Badge",
    name: "FNH Fighter",
    tier: "Prospect",
    category: "Attendance",
    description: "For playing in 10 total FNH games.",
    iconName: "badge-fnh-fighter",
    progressKind: "counter",
    counterOf: { stat: "fnhGamesTotal", target: 10 },
    triggerSources: ["attendance"],
    tags: ["FNH", "Milestone"]
  },
  {
    id: "digital-first-steps",
    kind: "Badge",
    name: "Digital First Steps",
    tier: "Prospect",
    category: "TrainingProgram",
    description: "For watching your very first video in the Online Foundation Program.",
    iconName: "badge-digital-first-steps",
    progressKind: "counter",
    counterOf: { stat: "totalVideos", target: 1 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "First"]
  },
  {
    id: "virtual-handles",
    kind: "Badge",
    name: "Virtual Handles",
    tier: "Prospect",
    category: "TrainingProgram",
    description: "For completing your first Skill video.",
    iconName: "badge-virtual-handles",
    progressKind: "counter",
    counterOf: { stat: "skillsCompleted", target: 1 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Skills", "First"]
  },
  {
    id: "remote-strength",
    kind: "Badge",
    name: "Remote Strength",
    tier: "Prospect",
    category: "TrainingProgram",
    description: "For completing your first Strength & Conditioning video.",
    iconName: "badge-remote-strength",
    progressKind: "counter",
    counterOf: { stat: "scCompleted", target: 1 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "Conditioning", "First"]
  },
  {
    id: "mindful-start",
    kind: "Badge",
    name: "Mindful Start",
    tier: "Prospect",
    category: "TrainingProgram",
    description: "For completing your first Basketball IQ video.",
    iconName: "badge-mindful-start",
    progressKind: "counter",
    counterOf: { stat: "iqCompleted", target: 1 },
    programTag: "Foundation",
    triggerSources: ["onlineTraining"],
    tags: ["Online", "IQ", "First"]
  },

  // ==================== LEGACY TROPHIES ====================
  {
    id: "coach-choice",
    kind: "Trophy",
    name: "Coach's Award",
    tier: "Legacy",
    category: "SeasonalLegacy",
    description: "Special recognition from coach for exceptional character and dedication.",
    iconName: "trophy-coaches-award",
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["Coach", "Special"]
  },
  {
    id: "most-improved",
    kind: "Trophy", 
    name: "Most Improved",
    tier: "Legacy",
    category: "SeasonalLegacy",
    description: "Awarded to the player who showed the greatest improvement over the season.",
    iconName: "trophy-mip",
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["Improvement", "Season"]
  },

  {
    id: "mvp-season",
    kind: "Trophy",
    name: "Season MVP",
    tier: "Legacy",
    category: "SeasonalLegacy", 
    description: "Most Valuable Player for the entire season.",
    iconName: "trophy-mvp",
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["MVP", "Season"]
  },
  {
    id: "defensive-player",
    kind: "Trophy",
    name: "Defensive Player",
    tier: "Legacy",
    category: "SeasonalLegacy",
    description: "Awarded to the player who had the greatest defensive impact.",
    iconName: "trophy-defensive",
    progressKind: "manual",
    triggerSources: ["coachAward"],
    tags: ["Defense", "Season"]
  },

];